In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_excel("D:/Github all files/Machine_learning_project2.0/Data_set/flats.xlsx")

In [4]:
df.head(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,https://www.99acres.com/2-bhk-bedroom-apartmen...,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,https://www.99acres.com/2-bhk-bedroom-apartmen...,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [5]:
df.shape

(3028, 20)

In [6]:
#information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3028 entries, 0 to 3027
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3028 non-null   object
 1   link             3028 non-null   object
 2   society          3027 non-null   object
 3   price            3008 non-null   object
 4   area             3015 non-null   object
 5   areaWithType     3009 non-null   object
 6   bedRoom          3009 non-null   object
 7   bathroom         3009 non-null   object
 8   balcony          3009 non-null   object
 9   additionalRoom   1695 non-null   object
 10  address          3003 non-null   object
 11  floorNum         3007 non-null   object
 12  facing           2128 non-null   object
 13  agePossession    3008 non-null   object
 14  nearbyLocations  2914 non-null   object
 15  description      3009 non-null   object
 16  furnishDetails   2204 non-null   object
 17  features         2595 non-null   object
 18  rating           2677 non-null   object
 19  property_id      3009 non-null   object
dtypes: object(20)
memory usage: 473.3+ KB

In [7]:
# checking the duplicate

df.duplicated().sum()

0

In [8]:
# checking the missing value
df.isnull().sum()

property_name         0
link                  0
society               1
price                20
area                 13
areaWithType         19
bedRoom              19
bathroom             19
balcony              19
additionalRoom     1333
address              25
floorNum             21
facing              900
agePossession        20
nearbyLocations     114
description          19
furnishDetails      824
features            433
rating              351
property_id          19
dtype: int64

In [9]:
#dropping link column and property_id columns

df.drop(columns=['link','property_id'],inplace=True)

In [10]:
df.head(1)

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [11]:
#rename the column area with area_per_sqft

df.rename(columns={'area':"area_per_sqft"}, inplace= True)
df.head(1)

,property_name,society,price,area_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [11]:
#society counts
df['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Emaar MGF Emerald Floors Premier3.8 ★                32
Smart World Orchard                                  32
Smart World Gems                                     32
DLF The Ultima4.0 ★                                  31
Paras Dews                                           31
DLF Regal Gardens3.9 ★                               30
M3M Woodshire4.0 ★                                   29
Shree Vardhman Flora3.8 ★                            29
Signature Global Solera3.7 ★                         28
La Vida by Tata Housing                              28
Godrej Nature Plus                                   27
Emaar Gurgaon Greens4.1 ★                            25
BPTP Terra3.8 ★                                      25
DLF New Town Heights 13.9 ★                          24
Vatika Gurgaon 213.7 ★                               24
Experion The Heartsong3.9 ★                          24
Eldeco Accolade3.8 ★                                 24
Bestech Park View Residency3.9 ★                     23
Emaar Palm Gardens4.1 ★                              22
ATS Triumph3.9 ★                                     22
Tata Primanti4.1 ★                                   22
M3M Heights                                          22
ROF Ananda                                           21
Sare Crescent Parc3.5 ★                              21
Experion Windchants3.8 ★                             20
Godrej 1014.0 ★                                      20
Antriksh Heights3.7 ★                                19
Sare Homes                                           19
Supertech Araville                                   19
ATS Tourmaline3.9 ★                                  18
Indiabulls Centrum Park3.7 ★                         18
Sobha City                                           18
CHD Avenue 713.6 ★                                   18
Mapsko Mount Ville4.1 ★                              18
Ambience Creacions                                   18
M3M Golfestate4.4 ★                                  17
M3M Skywalk                                          17
Godrej Summit3.7 ★                                   17
Conscient Heritage Max4.3 ★                          17
GLS Arawali Homes3.8 ★                               17
Pareena Coban Residences                             17
Bestech Park View Grand Spa4.3 ★                     16
HCBS Sports Ville3.6 ★                               16
Umang Monsoon Breeze                                 16
M3M Merlin3.7 ★                                      16
Godrej Oasis3.9 ★                                    16
Corona Optus3.9 ★                                    15
Emaar MGF The Palm Drive4.1 ★                        15
Ansal Heights 86                                     15
MVN Athens3.7 ★                                      14
The Close North4.0 ★                                 14
Ireo Skyon4.0 ★                                      14
Ireo Victory Valley4.1 ★                             14
Indiabulls Enigma                                    14
Ramsons Kshitij3.7 ★                                 14
Orchid Petals4.1 ★                                   14
Vatika The Seven Lamps3.8 ★                          14
Umang Winter Hills3.9 ★                              14
DLF The Primus3.9 ★                                  14
Imperia The Esfera                                   14
Puri Emerald Bay3.7 ★                                13
Central Park Flower Valley                           13
Ireo The Corridors                                   13
Bestech Park View Ananda4.2 ★                        13
Godrej Aria3.8 ★                                     11
DLF The Skycourt4.2 ★                                11
M3M Soulitude                                        11
TARC Maceo3.8 ★                                      11
Adani M2K Oyster Grande3.9 ★                         11
Alpha Corp GurgaonOne 844.0 ★                        11
Raheja Vedaanta3.6 ★                                 11
Breez Global Hill View                               11
SBTL Caladium                                        11
Pyramid Urban Homes 2                                10
Emaar MGF Palm Hills4.0 ★                            10
Zara Aavaas                                          10
Breez Global Heights4.2 ★                            10
Ramprastha The Edge Towers3.5 ★                      10
Capital Residences 360                               10
Puri Diplomatic Greens4.0 ★                          10
Signature Global Synera3.4 ★                         10
ATS Kocoon                                           10
DLF New Town Heights 24.0 ★                          10
ILD Greens4.1 ★                                      10
Godrej Air                                           10
Pivotal Devaan                                       10
Pareena Mi Casa                                       9
AIPL The Peaceful Homes3.9 ★                          9
Vatika City4.1 ★                                      9
Microtek Greenburg3.8 ★                               9
Bestech Park View Sanskruti4.2 ★                      9
Parsvnath Green Ville3.9 ★                            9
M3M Skycity                                           8
ss                                                    8
AVL 36 Gurgaon3.7 ★                                   8
Assotech Blith                                        8
Birla Navya                                           8
GLS Avenue 51                                         8
M3M Capital                                           8
Vatika Lifestyle Homes3.8 ★                           8
Orris Aster Court Premier                             8
Tulip Ivory3.5 ★                                      8
Bestech Altura                                        8
Emaar Digihomes                                       8
The Lions CGHS                                        8
Signature Andour Heights3.8 ★                         7
AIPL Zen Residences                                   7
Signature Global Orchard Avenue3.6 ★                  7
Vipul Lavanya3.9 ★                                    7
Orris Carnation Residency3.7 ★                        7
Sare Green ParC Phase 3                               7
Ireo The Grand Arch4.0 ★                              7
Signature Global City                                 7
Sare Crescent Parc Royal Greens Phase 1               7
Ansal Housing Highland Park                           7
Emaar Imperial Gardens3.8 ★                           7
Trisara Our Homes 3                                   7
Mapsko Casa Bella3.8 ★                                7
Greenopolis                                           6
HSIIDC Sidco Aravali                                  6
Signature Global Park 4                               6
Suncity Vatsal Valley                                 6
Sidhartha NCR One Phase 14.2 ★                        6
Hero Homes                                            6
Pioneer Araya3.8 ★                                    6
Bestech Park View City4.1 ★                           6
Shapoorji Pallonji Joyville Gurugram                  6
Kiran Residency                                       6
Pyramid Urban                                         6
BPTP Astaire Gardens3.7 ★                             6
Supertech Hues                                        6
Signature Global City 63A                             6
DLF Regency Park 13.6 ★                               6
Signature The Roselia3.6 ★                            6
Mapsko Royale Ville3.7 ★                              6
Bestech Park View Spa Next4.0 ★                       6
Parsvnath Exotica3.7 ★                                6
Ashiana Mulberry                                      6
M3M Sierra 68                                         6
Signature Global Grand IVA3.9 ★                       5
Ireo Uptown4.1 ★                                      5
Krisumi Waterfall Residences                          5
Pareena Laxmi Apartments3.6 ★                         5
Conscient Elevate                                     5
Central Park Resorts4.4 ★                             5
Central Park Flower Valley Aqua Front Towers          5
Tulip Monsella                                        5
M3M The Marina4.0 ★                                   5
Satya The Hermitage3.5 ★                              5
Apna Enclave                                          5
Godrej Habitat                                        5
Vatika City Homes3.9 ★                                5
Signature Global the Millennia                        5
DLF Park Place4.1 ★                                   5
DLF Regency Park 24.0 ★                               5
Signature Global City 37D Ph 2                        5
Green Court3.7 ★                                      5
Essel Towers                                          5
Silverglades The Melia                                5
Vatika Sovereign Park                                 5
Signature Global City 92                              5
Pioneer Park3.8 ★                                     5
Adani Brahma Samsara Vilasa                           5
Signature Global City 81                              5
Emaar MGF Emerald Estate3.8 ★                         5
ATS Marigold                                          5
Ashiana Anmol3.5 ★                                    5
Krrish Provence Estate                                4
Orris Aster Court                                     4
Signature The Serenas                                 4
Emaar Palm Heights                                    4
Godrej Icon                                           4
Global Hill View                                      4
ILD Grand                                             4
Corona Gracieux                                       4
Unitech Vistas                                        4
DLF New Town Heights3.7 ★                             4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
Unitech Fresco3.8 ★                                   4
Sare Petioles                                         4
Tata Gurgaon Gateway3.8 ★                             4
Railway Officers RPF Society                          4
Lotus Homz4.0 ★                                       4
Godrej Frontier3.7 ★                                  4
Raheja Navodaya3.6 ★                                  4
DLF The Skycourt                                      4
SS The Coralwood3.4 ★                                 4
Ramprastha Primera                                    4
Ramprastha Skyz                                       4
Prime Habitat                                         4
Maxworth City Residences                              3
Sidhartha NCR One                                     3
Unitech The Residences3.7 ★                           3
Deepak Minda                                          3
Tulip Purple                                          3
Raheja Atharva3.6 ★                                   3
Vatika Independent Floors3.8 ★                        3
Raheja Sampada                                        3
Unitech Uniworld Gardens3.8 ★                         3
Chintels Paradiso3.9 ★                                3
Puri Diplomatic Greens3.9 ★                           3
DLF Royalton Tower                                    3
Sidhartha NCR Greens4.3 ★                             3
Siddhartha Apartment                                  3
The Roselia 2                                         3
Kendriya Vihar4.1 ★                                   3
Valley View Estate                                    3
Whiteland Blissville                                  3
Signature Global Solera 2                             3
Pivotal Riddhi Siddhi                                 3
Guru Gram Haryana CGHS4.1 ★                           3
Unitech Sunbreeze                                     3
DLF The Arbour                                        3
Sare Green Parc 2                                     3
DLF Express Greens3.9 ★                               3
Tulip Petals3.6 ★                                     3
Shri Ram Apartments                                   3
Vatika Xpressions                                     3
Apex Our Homes                                        3
Shree Arihant Apartment                               3
Dhoot Time Residency4.0 ★                             3
Mahindra Aura4.2 ★                                    3
Shri Banke Bihari Society3.8 ★                        3
Sare Green Parc                                       3
Adani Aangan Arcade                                   3
AFNHB Jalvayu Vihar3.7 ★                              3
Sunischit Apartments                                  3
ATS Kocoon4.2 ★                                       3
Raheja Revanta                                        3
Spaze Privy3.9 ★                                      3
Tulip Lemon3.9 ★                                      3
Conscient Habitat3.6 ★                                3
Satya Element One                                     3
Suncity Platinum Towers                               3
Spaze Privy AT43.9 ★                                  3
Bestech Park View City 23.9 ★                         3
Spaze Privvy The Address3.9 ★                         3
Piedmont Taksila heights3.6 ★                         3
Paras Quartier                                        3
DLF Belvedere Towers3.8 ★                             3
AIPL Club Residences                                  3
My Home                                               3
Tulip White3.5 ★                                      3
Essel Tower                                           3
DLF Carlton Estate4.0 ★                               3
Smriti Apartment                                      3
Brisk Lumbini Terrace Homes                           3
SS Almeria                                            3
Sukhshanti Apartment                                  3
Unitech Heritage City                                 3
Jammu and Kashmir Bank Employees CGHS3.7 ★            3
Ambience Lagoon3.9 ★                                  3
Krrish Florence Estate                                3
DLF The Grove                                         3
Sapphire Eighty Three                                 3
Pyramid Elite                                         3
ROF Aalayas3.8 ★                                      2
Park Royal Apartment                                  2
BPTP Mansions Park Prime                              2
BPTP Pedestal                                         2
Sahara Grace                                          2
M3M Sky Lofts                                         2
Godrej Nature Plus Serenity                           2
DLF The Icon3.7 ★                                     2
Tulip Leaf                                            2
Emaar MGF The Enclave                                 2
Housing Board Colony                                  2
Mapsko Paradise3.9 ★                                  2
Professors Enclave CGHS                               2
Vipul Belmonte3.9 ★                                   2
Sidhivinayak Apartments                               2
Ardee City3.8 ★                                       2
Suncity Avenue 76                                     2
MRG World Ultimus                                     2
Samaspurkunj                                          2
HCBS Sports Ville                                     2
Paras Irene3.7 ★                                      2
Adani Aangan Galleria                                 2
Suncity Avenue 1023.9 ★                               2
Suncity Heights3.7 ★                                  2
DLF The Belaire3.9 ★                                  2
Ansal API Esencia3.7 ★                                2
Suposhaa Smartworld Orchard                           2
Raheja Atlantis3.8 ★                                  2
Palam Vihar Society                                   2
Ramprastha The Atrium3.4 ★                            2
Uphar lakshya homes                                   2
Mittal Surya Vihar                                    2
AWHO Shanti Vihar4.0 ★                                2
Vatika INXT Floors                                    2
Today Callidora                                       2
Ashiana Anmol                                         2
BPTP Amstoria3.8 ★                                    2
ss residency                                          2
Raheja Vanya                                          2
Central Park 2 Bellevue                               2
Tulip Orange3.9 ★                                     2
Chanderlok Society                                    2
Tulsiani Easy in Homes                                2
Ansal Heights3.2 ★                                    2
Residency Grand                                       2
Ramprastha City                                       2
Tulip Violet                                          2
Emaar MGF Palm Studios                                2
Landmark The Residency                                2
Mahindra Luminare4.0 ★                                2
Apartment                                             2
Vipul World Floors                                    2
CGHS Airport Apartment                                2
Ansal API Celebrity Suites                            2
The Penthouses at the Hibiscus                        2
SS Hibiscus                                           2
Puri The Aravallis                                    2
Silverglades Hightown Residences                      2
BPTP Freedom Park Life4.0 ★                           2
Vatika Emilia Floors3.7 ★                             2
M3M Latitude                                          2
Milan CGHS 9                                          2
Pioneer Urban Presidia                                2
Dlf City                                              2
Shapoorji Pallonji Joyville                           2
Element One Service                                   2
Oriental Valley CHS                                   2
Elan The Presidential                                 2
Viridian The Plaza 106                                2
The Close South3.9 ★                                  2
Breeze Global Heights                                 2
lagoon apartment                                      2
Supertech Hill Town                                   2
Aqua Front Towers                                     2
Lavanya Apartments                                    2
Ganga Apartment                                       2
Bhagwati Sadan                                        2
Signature Global The Millennia 3                      2
Supertech Hilltown                                    2
M3M Urbana                                            2
NBCC Heights3.9 ★                                     2
om appartments                                        2
Ambience Caitriona                                    2
Unitech Uniworld Gardens 23.4 ★                       2
Godrej Aria , sector 79 , Gurgaon                     2
Surendra Avenue 69                                    2
Bestech Park View Sanskruti4.1 ★                      2
DLF The Crest3.6 ★                                    2
M3M Ikonic                                            2
Bestech Spa Signature                                 2
Maruti Vihar                                          2
Vasant Appartments                                    2
Orchid Island4.2 ★                                    2
Green Campus CHS                                      2
ShreeRam Apartment II                                 1

In [12]:
df['society'].value_counts().shape

(639,)

In [13]:
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [14]:
df.sample(5)

,property_name,society,price,area_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
987,2 BHK Flat in Sector 85 Gurgaon,ss the leaf,1.22 Crore,"₹ 13,318/sq.ft.",Super Built up area 1772(164.62 sq.m.)Built Up...,2 Bedrooms,2 Bathrooms,3 Balconies,Store Room,"Sector 85 Gurgaon, Gurgaon, Haryana",16th of 26 Floors,North-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","Ss the leaf in sector 85, gurgaon is a ready-T...","['4 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Intercom Facility', 'Lift(s)', 'High Ceiling...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
1909,2 BHK Flat in Sohna,signature global park,54 Lac,"₹ 6,506/sq.ft.",Carpet area: 830 (77.11 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Sohna, Gurgaon, Haryana",2nd of 4 Floors,NaN,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...",Residential apartment for sell.Located in sohn...,[],"['Lift(s)', 'Swimming Pool', 'Fitness Centre /...","['Green Area5 out of 5', 'Construction5 out of..."
653,3 BHK Flat in Sector 22 Gurgaon,ambience creacions,4.78 Crore,"₹ 15,469/sq.ft.",Super Built up area 3090(287.07 sq.m.)Built Up...,3 Bedrooms,4 Bathrooms,3 Balconies,"Servant Room,Others","1001, Sector 22 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,West,1 to 5 Year Old,"['Moulsari Avenue', 'Ambience Mall', 'Old Delh...",This lovely 3 bhk apartment/flat in sector 22 ...,"['1 Water Purifier', '1 Fridge', '4 Fan', '1 E...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1742,3 BHK Flat in Sector 90 Gurgaon,dlf regal gardens,1.21 Crore,"₹ 6,926/sq.ft.",Super Built up area 1747(162.3 sq.m.),3 Bedrooms,3 Bathrooms,3+ Balconies,Others,"Multiple Options In, Sector 90 Gurgaon, Gurgao...",29th of 29 Floors,West,1 to 5 Year Old,"['SS Omnia, Sector 86', 'Numberdar market, IMT...",We have all size and multiple options in all f...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4.5 out ..."
2572,3 BHK Flat in Sector 86 Gurgaon,ansal heights 86,90 Lac,"₹ 5,325/sq.ft.",Built Up area: 1690 (157.01 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Sector 86,gurgaon, Sector 86 Gurgaon, Gurgaon,...",10th of 17 Floors,NaN,0 to 1 Year Old,"['IRIS Broadway Mall', 'Delhi Jaipur Expresswa...",Details can be seen on website,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [15]:
df['society'].value_counts().shape

(605,)

In [16]:
df.sample(5)

,property_name,society,price,area_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1988,4 BHK Flat in Sector 70A Gurgaon,bptp astaire gardens,1.7 Crore,"₹ 8,947/sq.ft.",Carpet area: 1900 (176.52 sq.m.),4 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sector 70A Gurgaon, Gurgaon, Haryana",1st of 2 Floors,North-East,1 to 5 Year Old,"['Sector 54 Chowk Metro Station', 'Airia Mall'...","On gurgaon spr, good potential as this area is...","['6 Fan', '1 Exhaust Fan', '3 Geyser', '20 Lig...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction5 out of..."
835,3 BHK Flat in Sector 65 Gurgaon,m3m golfestate,5.4 Crore,"₹ 18,126/sq.ft.",Super Built up area 2979(276.76 sq.m.),3 Bedrooms,4 Bathrooms,3 Balconies,"Study Room,Servant Room","Sector 65 Gurgaon, Gurgaon, Haryana",19th of 40 Floors,North-East,5 to 10 Year Old,"['Sector 54 Chowk Metro Station', 'Sahara Mall...",This 3 bhk apartment is available for sale in ...,"['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '5 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
72,2 BHK Flat in Sohna,signature the serenas,50 Lac,"₹ 9,406/sq.ft.",Carpet area: 531.57 (49.38 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sohna, Gurgaon, Haryana",6th of 14 Floors,NaN,0 to 1 Year Old,"['Signature Global Infinity Mall', 'Sohna Road...",Signature the serenas is one of the most popul...,[],"['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1057,3 BHK Flat in Sector 90 Gurgaon,shree vardhman flora,92 Lac,"₹ 4,717/sq.ft.",Carpet area: 1950 (181.16 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,Study Room,"Sector 90 Gurgaon, Gurgaon, Haryana",6th of 13 Floors,North,1 to 5 Year Old,"['IRIS Broadway Mall', 'Dwarka Expressway', 'S...",This lovely 3 bhk apartment/flat in sector 90 ...,"['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
496,1 BHK Flat in Sector 2 Gurgaon,ansal api celebrity suites,60 Lac,"₹ 8,163/sq.ft.",Super Built up area 735(68.28 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,NaN,"Sector 2 Gurgaon, Gurgaon, Haryana",5th of 15 Floors,North-East,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",1 bhk society apartment flat available for sal...,"['1 Wardrobe', '2 Fan', '1 Exhaust Fan', '1 Ge...","['Power Back-up', 'Feng Shui / Vaastu Complian...",NaN

In [17]:
df[df['price']== 'Price on Request']

,property_name,society,price,area_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
25,5 BHK Flat in Sector 1 Gurgaon,the new people apartments,Price on Request,NaN,Built Up area: 4500 (418.06 sq.m.),5 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana",Ground of 1 Floors,NaN,undefined,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Best in class property available at sector 1 l...,NaN,NaN,NaN
1645,4 BHK Flat in Sector 50 Gurgaon,ss hibiscus,Price on Request,NaN,Carpet area: 4800 (445.93 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Sector 50 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,East,5 to 10 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",4bedroom 4800sq.Ft middle floor apartment avai...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Water purifier', 'Swimming Pool',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1973,1 BHK Flat in Sector 31 Gurgaon,raheja atlantis,Price on Request,NaN,Carpet area: 650 (60.39 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,"Pooja Room,Study Room,Servant Room","Yes, Sector 31 Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,East,0 to 1 Year Old,"['Huda Metro Station', 'Reliance Fresh, Indira...",It is my property and good condition and good ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
2055,2 BHK Flat in Sector 79 Gurgaon,supertech araville,Price on Request,NaN,Built Up area: 1295 (120.31 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",15th of 15 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 15th floor (Of 18), super...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5..."
2358,2 BHK Flat in Sector 37D Gurgaon,the millennia 2,Price on Request,NaN,Carpet area: 552 (51.28 sq.m.),2 Bedrooms,1 Bathroom,1 Balcony,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",13rd of 13 Floors,NaN,undefined,"['Shri Balaji Hospital and Trauma Center', 'Sh...","1 bath, unfurnished, 13th floor (Of 13), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2523,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
2550,3 BHK Flat in Sector-2 Sohna,supertech hilltown,Price on Request,NaN,Built Up area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN
2641,2 BHK Flat in Sector 95A Gurgaon,the roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
2960,3 BHK Flat in Sector 104 Gurgaon,godrej summit,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
2973,4 BHK Flat in Gwal Pahari,krrish provence estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
2974,4 BHK Flat in Sector 95 Gurgaon,sidhartha ncr one phase,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [18]:
df[df['price']== 'Price on Request'].shape

(11, 18)

In [19]:
df = df[df['price']!= 'Price on Request']

In [32]:
df.head(5)

,property_name,society,price,area_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [20]:
def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [21]:
df['price'] = df['price'].str.split(' ')

In [57]:
df.sample(5)

,property_name,society,price,area_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
791,2 BHK Flat in Sector 99A Gurgaon,prime habitat,"[27.1, Lac]","₹ 6,049/sq.ft.",Carpet area: 448 (41.62 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Sector 99A Gurgaon, Gurgaon, Haryana",10th of 12 Floors,South,1 to 5 Year Old,"['The Hive Mall', 'Omaxe Gurgaon Mall', 'Gurug...",This lovely 2 bhk apartment/flat in sector 99a...,NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Environment4 out of 5', 'Lifestyle3 out of 5..."
1886,3 BHK Flat in Sector 106 Gurgaon,paras dews,"[1.14, Crore]","₹ 6,000/sq.ft.",Super Built up area 1900(176.52 sq.m.)Built Up...,3 Bedrooms,4 Bathrooms,3 Balconies,"Study Room,Servant Room","Sector 106 Gurgaon, Gurgaon, Haryana",8th of 24 Floors,South,1 to 5 Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...",Located in the popular residential address of ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN
2841,2 BHK Flat in Palam Vihar,rk tower,"[95, Lac]","₹ 9,595/sq.ft.",Carpet area: 990 (91.97 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Palam Vihar, Gurgaon, Haryana",1st of 4 Floors,South-East,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Lush green park facing, 1000sqft flat,24 + cct...","['1 Wardrobe', '30 Light', 'No AC', 'No Bed', ...","['Security / Fire Alarm', 'Intercom Facility',...","['Safety4 out of 5', 'Lifestyle5 out of 5', 'E..."
482,3 BHK Flat in Sector 67 Gurgaon,ireo victory valley,"[2.95, Crore]","₹ 12,235/sq.ft.",Super Built up area 2411(223.99 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,Servant Room,"Golf Course Extension Road, Sector 67 Gurgaon,...",10th of 51 Floors,North-West,1 to 5 Year Old,"['AIPL Joy Street Mall', 'Golf Course Extensio...",100% genuine deals available in ireo victory v...,"['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
586,3 BHK Flat in Sector 113 Gurgaon,la vida by tata housing,"[2.78, Crore]","₹ 10,334/sq.ft.",Super Built up area 2690(249.91 sq.m.)Built Up...,3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"Dwarka Expressway, Sector 113 Gurgaon , Gurgao...",5th of 25 Floors,North-East,1 to 5 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",Experience a new style of living with la vida ...,"['1 Water Purifier', '1 Light', 'No AC', 'No B...","['Centrally Air Conditioned', 'Water purifier'...",NaN

In [33]:
def treat_price(x):
    # Check if x is a float, return as is if true
    if isinstance(x, float):
        return x
    
    # Check if x is a list and contains at least two elements
    if isinstance(x, list) and len(x) >= 2:
        # Check if the second element is 'Lac'
        if x[1] == 'Lac':
            return round(float(x[0])/100, 2)  # Convert Lac to Crore
        else:
            return round(float(x[0]), 2)  # For Crore values
    
    # If x is not as expected, return NaN or handle as needed
    return float('nan')

In [49]:
df['price'] = df['price'].apply(treat_price)

In [50]:
df.head(5)

,property_name,society,price,area_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [51]:
df.rename(columns={'area_per_sqft':'price_per_sqft'}, inplace= True)

In [52]:
df.head(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [53]:
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 10,000/sq.ft.     19
₹ 12,500/sq.ft.     16
₹ 8,000/sq.ft.      16
₹ 6,666/sq.ft.      13
₹ 5,000/sq.ft.      13
₹ 7,500/sq.ft.      12
₹ 8,333/sq.ft.      12
₹ 6,000/sq.ft.      11
₹ 8,461/sq.ft.       9
₹ 7,000/sq.ft.       8
₹ 9,000/sq.ft.       8
₹ 12,000/sq.ft.      8
₹ 11,111/sq.ft.      7
₹ 8,928/sq.ft.       6
₹ 11,500/sq.ft.      6
₹ 9,230/sq.ft.       6
₹ 5,500/sq.ft.       6
₹ 6,578/sq.ft.       6
₹ 8,888/sq.ft.       6
₹ 7,142/sq.ft.       5
₹ 10,714/sq.ft.      5
₹ 8,108/sq.ft.       5
₹ 8,571/sq.ft.       5
₹ 7,407/sq.ft.       5
₹ 16,000/sq.ft.      5
₹ 8,205/sq.ft.       5
₹ 11,428/sq.ft.      5
₹ 6,500/sq.ft.       5
₹ 4,444/sq.ft.       5
₹ 5,556/sq.ft.       5
₹ 5,600/sq.ft.       5
₹ 14,242/sq.ft.      5
₹ 4,666/sq.ft.       5
₹ 4,615/sq.ft.       5
₹ 5,384/sq.ft.       5
₹ 7,692/sq.ft.       5
₹ 7,641/sq.ft.       5
₹ 9,210/sq.ft.       4
₹ 8,358/sq.ft.       4
₹ 15,000/sq.ft.      4
₹ 4,814/sq.ft.       4
₹ 7,317/sq.ft.       4
₹ 16,666/sq.ft.      4
₹ 13,913/sq.ft.      4
₹ 14,418/sq.ft.      4
₹ 4,854/sq.ft.       4
₹ 5,660/sq.ft.       4
₹ 6,250/sq.ft.       4
₹ 7,496/sq.ft.       4
₹ 9,822/sq.ft.       4
₹ 9,090/sq.ft.       4
₹ 7,272/sq.ft.       4
₹ 7,812/sq.ft.       4
₹ 8,787/sq.ft.       4
₹ 15,384/sq.ft.      4
₹ 8,445/sq.ft.       4
₹ 8,500/sq.ft.       4
₹ 8,484/sq.ft.       4
₹ 8,163/sq.ft.       4
₹ 6,735/sq.ft.       4
₹ 10,416/sq.ft.      4
₹ 13,636/sq.ft.      4
₹ 8,784/sq.ft.       4
₹ 4,500/sq.ft.       4
₹ 8,139/sq.ft.       4
₹ 7,250/sq.ft.       4
₹ 11,666/sq.ft.      4
₹ 4,687/sq.ft.       4
₹ 13,750/sq.ft.      4
₹ 10,383/sq.ft.      4
₹ 8,474/sq.ft.       4
₹ 8,043/sq.ft.       4
₹ 8,432/sq.ft.       4
₹ 5,319/sq.ft.       3
₹ 9,615/sq.ft.       3
₹ 5,856/sq.ft.       3
₹ 5,735/sq.ft.       3
₹ 8,181/sq.ft.       3
₹ 6,470/sq.ft.       3
₹ 10,555/sq.ft.      3
₹ 10,204/sq.ft.      3
₹ 5,397/sq.ft.       3
₹ 7,179/sq.ft.       3
₹ 16,470/sq.ft.      3
₹ 9,900/sq.ft.       3
₹ 13,000/sq.ft.      3
₹ 6,593/sq.ft.       3
₹ 8,886/sq.ft.       3
₹ 6,476/sq.ft.       3
₹ 6,818/sq.ft.       3
₹ 8,078/sq.ft.       3
₹ 4,820/sq.ft.       3
₹ 7,750/sq.ft.       3
₹ 4,800/sq.ft.       3
₹ 8,215/sq.ft.       3
₹ 8,222/sq.ft.       3
₹ 5,878/sq.ft.       3
₹ 7,083/sq.ft.       3
₹ 6,542/sq.ft.       3
₹ 13,392/sq.ft.      3
₹ 8,450/sq.ft.       3
₹ 8,620/sq.ft.       3
₹ 8,389/sq.ft.       3
₹ 6,667/sq.ft.       3
₹ 4,105/sq.ft.       3
₹ 8,750/sq.ft.       3
₹ 7,865/sq.ft.       3
₹ 7,400/sq.ft.       3
₹ 9,904/sq.ft.       3
₹ 6,644/sq.ft.       3
₹ 10,139/sq.ft.      3
₹ 7,586/sq.ft.       3
₹ 14,000/sq.ft.      3
₹ 6,921/sq.ft.       3
₹ 9,473/sq.ft.       3
₹ 7,948/sq.ft.       3
₹ 9,500/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 6,404/sq.ft.       3
₹ 7,056/sq.ft.       3
₹ 7,302/sq.ft.       3
₹ 9,011/sq.ft.       3
₹ 6,421/sq.ft.       3
₹ 8,606/sq.ft.       3
₹ 10,638/sq.ft.      3
₹ 6,086/sq.ft.       3
₹ 8,604/sq.ft.       3
₹ 14,430/sq.ft.      3
₹ 13,870/sq.ft.      3
₹ 11,363/sq.ft.      3
₹ 7,150/sq.ft.       3
₹ 7,549/sq.ft.       3
₹ 14,254/sq.ft.      3
₹ 7,954/sq.ft.       3
₹ 8,080/sq.ft.       3
₹ 4,210/sq.ft.       3
₹ 8,400/sq.ft.       3
₹ 11,000/sq.ft.      3
₹ 6,387/sq.ft.       3
₹ 16,969/sq.ft.      3
₹ 10,500/sq.ft.      3
₹ 5,833/sq.ft.       3
₹ 4,513/sq.ft.       3
₹ 7,467/sq.ft.       3
₹ 9,972/sq.ft.       3
₹ 8,148/sq.ft.       3
₹ 5,238/sq.ft.       3
₹ 8,532/sq.ft.       3
₹ 5,325/sq.ft.       3
₹ 7,541/sq.ft.       3
₹ 8,453/sq.ft.       2
₹ 8,410/sq.ft.       2
₹ 10,936/sq.ft.      2
₹ 7,945/sq.ft.       2
₹ 6,373/sq.ft.       2
₹ 8,252/sq.ft.       2
₹ 18,271/sq.ft.      2
₹ 7,631/sq.ft.       2
₹ 6,422/sq.ft.       2
₹ 5,896/sq.ft.       2
₹ 10,516/sq.ft.      2
₹ 8,166/sq.ft.       2
₹ 16,985/sq.ft.      2
₹ 12,212/sq.ft.      2
₹ 13,430/sq.ft.      2
₹ 16,608/sq.ft.      2
₹ 7,185/sq.ft.       2
₹ 8,903/sq.ft.       2
₹ 5,674/sq.ft.       2
₹ 5,528/sq.ft.       2
₹ 6,655/sq.ft.       2
₹ 9,025/sq.ft.       2
₹ 200,000/sq.ft.     2
₹ 8,279/sq.ft.       2
₹ 7,608/sq.ft.       2
₹ 10,699/sq.ft.      2
₹ 9,105/sq.ft.       2
₹ 13,991/sq.ft.      2
₹ 11,726/sq.ft.      2
₹ 7,878/sq.ft.       2
₹ 19,747/sq.ft.      2
₹ 9,978/sq.ft.       2
₹ 6,313/sq.ft.       2
₹ 11,125/sq.ft.      2
₹ 9,854/sq.ft.       2
₹ 7,359/sq.ft.       2
₹ 21,538/sq.ft.      2
₹ 8,834/sq.ft.       2
₹ 5,649/sq.ft.       2
₹ 8,600/sq.ft.       2
₹ 5,513/sq.ft.       2
₹ 4,909/sq.ft.       2
₹ 3,911/sq.ft.       2
₹ 11,412/sq.ft.      2
₹ 8,846/sq.ft.       2
₹ 17,039/sq.ft.      2
₹ 6,333/sq.ft.       2
₹ 11,765/sq.ft.      2
₹ 5,839/sq.ft.       2
₹ 7,610/sq.ft.       2
₹ 16,858/sq.ft.      2
₹ 6,315/sq.ft.       2
₹ 6,053/sq.ft.       2
₹ 4,856/sq.ft.       2
₹ 5,056/sq.ft.       2
₹ 9,743/sq.ft.       2
₹ 7,350/sq.ft.       2
₹ 15,416/sq.ft.      2
₹ 6,987/sq.ft.       2
₹ 13,076/sq.ft.      2
₹ 15,551/sq.ft.      2
₹ 14,237/sq.ft.      2
₹ 8,433/sq.ft.       2
₹ 20,687/sq.ft.      2
₹ 15,294/sq.ft.      2
₹ 4,857/sq.ft.       2
₹ 6,049/sq.ft.       2
₹ 8,519/sq.ft.       2
₹ 9,922/sq.ft.       2
₹ 9,797/sq.ft.       2
₹ 8,897/sq.ft.       2
₹ 9,672/sq.ft.       2
₹ 8,733/sq.ft.       2
₹ 13,108/sq.ft.      2
₹ 6,679/sq.ft.       2
₹ 4,327/sq.ft.       2
₹ 9,007/sq.ft.       2
₹ 7,908/sq.ft.       2
₹ 8,632/sq.ft.       2
₹ 15,263/sq.ft.      2
₹ 11,336/sq.ft.      2
₹ 16,747/sq.ft.      2
₹ 6,141/sq.ft.       2
₹ 8,290/sq.ft.       2
₹ 8,376/sq.ft.       2
₹ 19,767/sq.ft.      2
₹ 13,270/sq.ft.      2
₹ 6,406/sq.ft.       2
₹ 14,785/sq.ft.      2
₹ 7,716/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 12,012/sq.ft.      2
₹ 9,791/sq.ft.       2
₹ 7,987/sq.ft.       2
₹ 8,031/sq.ft.       2
₹ 8,814/sq.ft.       2
₹ 3,477/sq.ft.       2
₹ 8,294/sq.ft.       2
₹ 5,744/sq.ft.       2
₹ 6,382/sq.ft.       2
₹ 14,683/sq.ft.      2
₹ 14,303/sq.ft.      2
₹ 5,177/sq.ft.       2
₹ 8,305/sq.ft.       2
₹ 9,742/sq.ft.       2
₹ 10,553/sq.ft.      2
₹ 9,950/sq.ft.       2
₹ 6,839/sq.ft.       2
₹ 8,411/sq.ft.       2
₹ 8,283/sq.ft.       2
₹ 5,929/sq.ft.       2
₹ 15,195/sq.ft.      2
₹ 10,489/sq.ft.      2
₹ 11,727/sq.ft.      2
₹ 9,139/sq.ft.       2
₹ 9,620/sq.ft.       2
₹ 9,589/sq.ft.       2
₹ 6,774/sq.ft.       2
₹ 5,564/sq.ft.       2
₹ 6,571/sq.ft.       2
₹ 15,454/sq.ft.      2
₹ 9,550/sq.ft.       2
₹ 8,424/sq.ft.       2
₹ 9,565/sq.ft.       2
₹ 6,153/sq.ft.       2
₹ 8,159/sq.ft.       2
₹ 8,324/sq.ft.       2
₹ 19,000/sq.ft.      2
₹ 8,536/sq.ft.       2
₹ 6,465/sq.ft.       2
₹ 4,761/sq.ft.       2
₹ 8,835/sq.ft.       2
₹ 8,412/sq.ft.       2
₹ 8,670/sq.ft.       2
₹ 8,024/sq.ft.       2
₹ 6,896/sq.ft.       2
₹ 11,715/sq.ft.      2
₹ 8,974/sq.ft.       2
₹ 9,306/sq.ft.       2
₹ 5,454/sq.ft.       2
₹ 7,174/sq.ft.       2
₹ 6,938/sq.ft.       2
₹ 9,020/sq.ft.       2
₹ 6,402/sq.ft.       2
₹ 7,765/sq.ft.       2
₹ 16,363/sq.ft.      2
₹ 9,074/sq.ft.       2
₹ 5,671/sq.ft.       2
₹ 19,882/sq.ft.      2
₹ 14,615/sq.ft.      2
₹ 13,709/sq.ft.      2
₹ 8,237/sq.ft.       2
₹ 8,457/sq.ft.       2
₹ 4,307/sq.ft.       2
₹ 7,817/sq.ft.       2
₹ 9,022/sq.ft.       2
₹ 11,992/sq.ft.      2
₹ 7,223/sq.ft.       2
₹ 6,811/sq.ft.       2
₹ 5,982/sq.ft.       2
₹ 9,128/sq.ft.       2
₹ 14,285/sq.ft.      2
₹ 5,588/sq.ft.       2
₹ 5,658/sq.ft.       2
₹ 8,518/sq.ft.       2
₹ 6,455/sq.ft.       2
₹ 8,100/sq.ft.       2
₹ 5,825/sq.ft.       2
₹ 7,014/sq.ft.       2
₹ 10,596/sq.ft.      2
₹ 6,588/sq.ft.       2
₹ 5,820/sq.ft.       2
₹ 12,222/sq.ft.      2
₹ 18,518/sq.ft.      2
₹ 3,695/sq.ft.       2
₹ 8,756/sq.ft.       2
₹ 6,428/sq.ft.       2
₹ 9,482/sq.ft.       2
₹ 5,100/sq.ft.       2
₹ 5,599/sq.ft.       2
₹ 4,745/sq.ft.       2
₹ 7,449/sq.ft.       2
₹ 5,683/sq.ft.       2
₹ 5,517/sq.ft.       2
₹ 8,947/sq.ft.       2
₹ 13,343/sq.ft.      2
₹ 6,254/sq.ft.       2
₹ 7,850/sq.ft.       2
₹ 6,243/sq.ft.       2
₹ 13,928/sq.ft.      2
₹ 7,097/sq.ft.       2
₹ 5,252/sq.ft.       2
₹ 6,692/sq.ft.       2
₹ 7,058/sq.ft.       2
₹ 7,490/sq.ft.       2
₹ 12,444/sq.ft.      2
₹ 11,250/sq.ft.      2
₹ 6,076/sq.ft.       2
₹ 10,237/sq.ft.      2
₹ 4,080/sq.ft.       2
₹ 5,808/sq.ft.       2
₹ 7,863/sq.ft.       2
₹ 10,651/sq.ft.      2
₹ 5,828/sq.ft.       2
₹ 7,758/sq.ft.       2
₹ 9,433/sq.ft.       2
₹ 5,725/sq.ft.       2
₹ 7,751/sq.ft.       2
₹ 15,500/sq.ft.      2
₹ 10,545/sq.ft.      2
₹ 6,029/sq.ft.       2
₹ 11,694/sq.ft.      2
₹ 5,150/sq.ft.       2
₹ 9,642/sq.ft.       2
₹ 5,980/sq.ft.       2
₹ 6,647/sq.ft.       2
₹ 6,825/sq.ft.       2
₹ 11,505/sq.ft.      2
₹ 12,022/sq.ft.      2
₹ 6,209/sq.ft.       2
₹ 8,609/sq.ft.       2
₹ 9,449/sq.ft.       2
₹ 11,724/sq.ft.      2
₹ 18,000/sq.ft.      2
₹ 8,310/sq.ft.       2
₹ 9,062/sq.ft.       2
₹ 9,166/sq.ft.       2
₹ 8,504/sq.ft.       2
₹ 7,530/sq.ft.       2
₹ 6,217/sq.ft.       2
₹ 8,006/sq.ft.       2
₹ 33,198/sq.ft.      2
₹ 4,400/sq.ft.       2
₹ 5,284/sq.ft.       2
₹ 5,470/sq.ft.       2
₹ 6,506/sq.ft.       2
₹ 7,627/sq.ft.       2
₹ 6,967/sq.ft.       2
₹ 6,789/sq.ft.       2
₹ 7,780/sq.ft.       2
₹ 7,782/sq.ft.       2
₹ 6,111/sq.ft.       2
₹ 13,769/sq.ft.      2
₹ 7,396/sq.ft.       2
₹ 6,024/sq.ft.       2
₹ 5,882/sq.ft.       2
₹ 8,053/sq.ft.       2
₹ 10,666/sq.ft.      2
₹ 9,286/sq.ft.       2
₹ 5,797/sq.ft.       2
₹ 5,038/sq.ft.       2
₹ 10,531/sq.ft.      2
₹ 6,377/sq.ft.       2
₹ 8,972/sq.ft.       2
₹ 6,429/sq.ft.       2
₹ 6,061/sq.ft.       2
₹ 6,325/sq.ft.       2
₹ 6,739/sq.ft.       2
₹ 10,384/sq.ft.      2
₹ 13,500/sq.ft.      2
₹ 7,200/sq.ft.       2
₹ 6,983/sq.ft.       2
₹ 6,686/sq.ft.       2
₹ 10,526/sq.ft.      2
₹ 10,601/sq.ft.      2
₹ 8,618/sq.ft.       2
₹ 7,585/sq.ft.       2
₹ 8,582/sq.ft.       2
₹ 9,876/sq.ft.       2
₹ 9,909/sq.ft.       2
₹ 9,146/sq.ft.       2
₹ 11,755/sq.ft.      2
₹ 41,245/sq.ft.      2
₹ 5,405/sq.ft.       2
₹ 15,151/sq.ft.      2
₹ 5,714/sq.ft.       2
₹ 6,318/sq.ft.       2
₹ 6,950/sq.ft.       2
₹ 6,538/sq.ft.       2
₹ 8,720/sq.ft.       2
₹ 11,700/sq.ft.      2
₹ 7,234/sq.ft.       2
₹ 6,129/sq.ft.       2
₹ 4,723/sq.ft.       2
₹ 9,135/sq.ft.       2
₹ 7,796/sq.ft.       2
₹ 4,818/sq.ft.       2
₹ 10,476/sq.ft.      2
₹ 4,200/sq.ft.       2
₹ 6,361/sq.ft.       2
₹ 6,493/sq.ft.       2
₹ 6,859/sq.ft.       2
₹ 6,551/sq.ft.       2
₹ 9,677/sq.ft.       2
₹ 13,333/sq.ft.      2
₹ 12,250/sq.ft.      2
₹ 6,722/sq.ft.       2
₹ 6,200/sq.ft.       2
₹ 7,846/sq.ft.       2
₹ 7,297/sq.ft.       2
₹ 6,338/sq.ft.       2
₹ 6,420/sq.ft.       2
₹ 11,529/sq.ft.      2
₹ 9,027/sq.ft.       2
₹ 10,018/sq.ft.      2
₹ 6,178/sq.ft.       2
₹ 5,641/sq.ft.       2
₹ 8,524/sq.ft.       2
₹ 8,611/sq.ft.       2
₹ 8,036/sq.ft.       2
₹ 8,035/sq.ft.       2
₹ 6,569/sq.ft.       2
₹ 14,545/sq.ft.      2
₹ 10,599/sq.ft.      2
₹ 5,128/sq.ft.       2
₹ 6,812/sq.ft.       2
₹ 5,521/sq.ft.       2
₹ 9,600/sq.ft.       2
₹ 11,627/sq.ft.      2
₹ 7,857/sq.ft.       2
₹ 7,574/sq.ft.       2
₹ 7,225/sq.ft.       2
₹ 5,424/sq.ft.       2
₹ 6,510/sq.ft.       2
₹ 6,353/sq.ft.       2
₹ 6,190/sq.ft.       2
₹ 14,214/sq.ft.      2
₹ 58/sq.ft.          2
₹ 9,182/sq.ft.       2
₹ 12,782/sq.ft.      2
₹ 6,927/sq.ft.       2
₹ 5,111/sq.ft.       2
₹ 17,619/sq.ft.      2
₹ 14,478/sq.ft.      2
₹ 11,333/sq.ft.      2
₹ 11,516/sq.ft.      2
₹ 16,960/sq.ft.      2
₹ 6,206/sq.ft.       2
₹ 7,391/sq.ft.       2
₹ 13,224/sq.ft.      2
₹ 10,603/sq.ft.      2
₹ 7,248/sq.ft.       2
₹ 4,651/sq.ft.       2
₹ 8,206/sq.ft.       2
₹ 8,517/sq.ft.       2
₹ 6,985/sq.ft.       2
₹ 5,291/sq.ft.       2
₹ 8,521/sq.ft.       2
₹ 11,028/sq.ft.      2
₹ 6,597/sq.ft.       2
₹ 18,181/sq.ft.      2
₹ 6,134/sq.ft.       2
₹ 9,452/sq.ft.       2
₹ 7,825/sq.ft.       2
₹ 5,786/sq.ft.       2
₹ 13,281/sq.ft.      2
₹ 14,800/sq.ft.      2
₹ 4,271/sq.ft.       2
₹ 10,370/sq.ft.      2
₹ 5,463/sq.ft.       2
₹ 5,681/sq.ft.       2
₹ 4,000/sq.ft.       2
₹ 7,884/sq.ft.       2
₹ 12,777/sq.ft.      2
₹ 9,263/sq.ft.       2
₹ 5,189/sq.ft.       2
₹ 5,899/sq.ft.       2
₹ 15,998/sq.ft.      2
₹ 8,072/sq.ft.       2
₹ 14,583/sq.ft.      2
₹ 7,727/sq.ft.       2
₹ 6,702/sq.ft.       2
₹ 9,259/sq.ft.       2
₹ 6,189/sq.ft.       2
₹ 6,616/sq.ft.       2
₹ 14,257/sq.ft.      2
₹ 5,614/sq.ft.       2
₹ 8,075/sq.ft.       2
₹ 9,851/sq.ft.       2
₹ 9,333/sq.ft.       2
₹ 13,383/sq.ft.      2
₹ 7,547/sq.ft.       1
₹ 16,230/sq.ft.      1
₹ 11,538/sq.ft.      1
₹ 6,256/sq.ft.       1
₹ 9,696/sq.ft.       1
₹ 22,346/sq.ft.      1
₹ 17,378/sq.ft.      1
₹ 4,108/sq.ft.       1
₹ 9/sq.ft.           1
₹ 10,754/sq.ft.      1
₹ 8,840/sq.ft.       1
₹ 23,344/sq.ft.      1
₹ 5,904/sq.ft.       1
₹ 15,124/sq.ft.      1
₹ 7,561/sq.ft.       1
₹ 15,262/sq.ft.      1
₹ 6,751/sq.ft.       1
₹ 13,522/sq.ft.      1
₹ 10,309/sq.ft.      1
₹ 15,360/sq.ft.      1
₹ 14,632/sq.ft.      1
₹ 10,723/sq.ft.      1
₹ 6,485/sq.ft.       1
₹ 6,176/sq.ft.       1
₹ 6,194/sq.ft.       1
₹ 6,033/sq.ft.       1
₹ 13,296/sq.ft.      1
₹ 6,648/sq.ft.       1
₹ 13,953/sq.ft.      1
₹ 17,543/sq.ft.      1
₹ 8,124/sq.ft.       1
₹ 6,979/sq.ft.       1
₹ 8,558/sq.ft.       1
₹ 6,554/sq.ft.       1
₹ 11,923/sq.ft.      1
₹ 14,358/sq.ft.      1
₹ 14,658/sq.ft.      1
₹ 5,813/sq.ft.       1
₹ 20,666/sq.ft.      1
₹ 10,306/sq.ft.      1
₹ 9,531/sq.ft.       1
₹ 9,002/sq.ft.       1
₹ 9,380/sq.ft.       1
₹ 7,066/sq.ft.       1
₹ 10,627/sq.ft.      1
₹ 11,386/sq.ft.      1
₹ 11,423/sq.ft.      1
₹ 9,370/sq.ft.       1
₹ 9,264/sq.ft.       1
₹ 18,688/sq.ft.      1
₹ 7,006/sq.ft.       1
₹ 7,679/sq.ft.       1
₹ 7,931/sq.ft.       1
₹ 17,271/sq.ft.      1
₹ 3,713/sq.ft.       1
₹ 7,227/sq.ft.       1
₹ 4,886/sq.ft.       1
₹ 5,296/sq.ft.       1
₹ 8,297/sq.ft.       1
₹ 9,664/sq.ft.       1
₹ 11,178/sq.ft.      1
₹ 7,321/sq.ft.       1
₹ 6,894/sq.ft.       1
₹ 7,917/sq.ft.       1
₹ 11,094/sq.ft.      1
₹ 20,707/sq.ft.      1
₹ 6,272/sq.ft.       1
₹ 8,349/sq.ft.       1
₹ 6,113/sq.ft.       1
₹ 14,680/sq.ft.      1
₹ 6,083/sq.ft.       1
₹ 11,869/sq.ft.      1
₹ 10,031/sq.ft.      1
₹ 14,783/sq.ft.      1
₹ 10,101/sq.ft.      1
₹ 8,920/sq.ft.       1
₹ 10,452/sq.ft.      1
₹ 5,621/sq.ft.       1
₹ 4,869/sq.ft.       1
₹ 10,172/sq.ft.      1
₹ 4,579/sq.ft.       1
₹ 8,494/sq.ft.       1
₹ 14,603/sq.ft.      1
₹ 4,545/sq.ft.       1
₹ 12,791/sq.ft.      1
₹ 6,319/sq.ft.       1
₹ 15,102/sq.ft.      1
₹ 12,420/sq.ft.      1
₹ 8,026/sq.ft.       1
₹ 14,379/sq.ft.      1
₹ 10,924/sq.ft.      1
₹ 12,489/sq.ft.      1
₹ 8,953/sq.ft.       1
₹ 9,714/sq.ft.       1
₹ 4,219/sq.ft.       1
₹ 18,392/sq.ft.      1
₹ 7,779/sq.ft.       1
₹ 5,443/sq.ft.       1
₹ 3,671/sq.ft.       1
₹ 7,293/sq.ft.       1
₹ 5,739/sq.ft.       1
₹ 8,674/sq.ft.       1
₹ 5,329/sq.ft.       1
₹ 9,076/sq.ft.       1
₹ 8,986/sq.ft.       1
₹ 4,933/sq.ft.       1
₹ 9,125/sq.ft.       1
₹ 10,094/sq.ft.      1
₹ 7,988/sq.ft.       1
₹ 7,068/sq.ft.       1
₹ 11,854/sq.ft.      1
₹ 9,130/sq.ft.       1
₹ 591/sq.ft.         1
₹ 13,936/sq.ft.      1
₹ 4,941/sq.ft.       1
₹ 8,111/sq.ft.       1
₹ 4,729/sq.ft.       1
₹ 10,483/sq.ft.      1
₹ 4,375/sq.ft.       1
₹ 6,849/sq.ft.       1
₹ 6,881/sq.ft.       1
₹ 8,907/sq.ft.       1
₹ 7,164/sq.ft.       1
₹ 9,219/sq.ft.       1
₹ 4,971/sq.ft.       1
₹ 10,888/sq.ft.      1
₹ 8,856/sq.ft.       1
₹ 10,773/sq.ft.      1
₹ 10,017/sq.ft.      1
₹ 10,257/sq.ft.      1
₹ 11,407/sq.ft.      1
₹ 11,074/sq.ft.      1
₹ 10,408/sq.ft.      1
₹ 13,425/sq.ft.      1
₹ 5,931/sq.ft.       1
₹ 9,856/sq.ft.       1
₹ 22,222/sq.ft.      1
₹ 8,042/sq.ft.       1
₹ 8,557/sq.ft.       1
₹ 8,850/sq.ft.       1
₹ 11,276/sq.ft.      1
₹ 6,022/sq.ft.       1
₹ 8,970/sq.ft.       1
₹ 8,120/sq.ft.       1
₹ 14,795/sq.ft.      1
₹ 6,951/sq.ft.       1
₹ 11,944/sq.ft.      1
₹ 14,267/sq.ft.      1
₹ 8,522/sq.ft.       1
₹ 10,815/sq.ft.      1
₹ 8,737/sq.ft.       1
₹ 13,575/sq.ft.      1
₹ 6,502/sq.ft.       1
₹ 6,998/sq.ft.       1
₹ 8,264/sq.ft.       1
₹ 8,052/sq.ft.       1
₹ 7,951/sq.ft.       1
₹ 4,179/sq.ft.       1
₹ 8,347/sq.ft.       1
₹ 13,989/sq.ft.      1
₹ 11,654/sq.ft.      1
₹ 11,741/sq.ft.      1
₹ 10,163/sq.ft.      1
₹ 11,346/sq.ft.      1
₹ 8,123/sq.ft.       1
₹ 11,251/sq.ft.      1
₹ 19,943/sq.ft.      1
₹ 20,995/sq.ft.      1
₹ 17,729/sq.ft.      1
₹ 5,590/sq.ft.       1
₹ 8,240/sq.ft.       1
₹ 10,283/sq.ft.      1
₹ 17,691/sq.ft.      1
₹ 4,637/sq.ft.       1
₹ 10,004/sq.ft.      1
₹ 4,587/sq.ft.       1
₹ 5,041/sq.ft.       1
₹ 8,707/sq.ft.       1
₹ 9,701/sq.ft.       1
₹ 9,734/sq.ft.       1
₹ 10,134/sq.ft.      1
₹ 15,901/sq.ft.      1
₹ 8,622/sq.ft.       1
₹ 4,923/sq.ft.       1
₹ 10,578/sq.ft.      1
₹ 11,061/sq.ft.      1
₹ 10,656/sq.ft.      1
₹ 7,360/sq.ft.       1
₹ 8,790/sq.ft.       1
₹ 11,605/sq.ft.      1
₹ 10,071/sq.ft.      1
₹ 9,252/sq.ft.       1
₹ 9,583/sq.ft.       1
₹ 13,480/sq.ft.      1
₹ 11,989/sq.ft.      1
₹ 7,714/sq.ft.       1
₹ 9,639/sq.ft.       1
₹ 15,130/sq.ft.      1
₹ 7,654/sq.ft.       1
₹ 4,821/sq.ft.       1
₹ 9,136/sq.ft.       1
₹ 9,102/sq.ft.       1
₹ 3,516/sq.ft.       1
₹ 5,076/sq.ft.       1
₹ 9,843/sq.ft.       1
₹ 5,910/sq.ft.       1
₹ 9,459/sq.ft.       1
₹ 9,569/sq.ft.       1
₹ 9,513/sq.ft.       1
₹ 6,159/sq.ft.       1
₹ 5,950/sq.ft.       1
₹ 4,927/sq.ft.       1
₹ 6,778/sq.ft.       1
₹ 8,554/sq.ft.       1
₹ 6,905/sq.ft.       1
₹ 6,346/sq.ft.       1
₹ 8,487/sq.ft.       1
₹ 11,525/sq.ft.      1
₹ 10,903/sq.ft.      1
₹ 10,205/sq.ft.      1
₹ 5,965/sq.ft.       1
₹ 7,872/sq.ft.       1
₹ 8,404/sq.ft.       1
₹ 8,095/sq.ft.       1
₹ 6,077/sq.ft.       1
₹ 8,266/sq.ft.       1
₹ 13,921/sq.ft.      1
₹ 15,982/sq.ft.      1
₹ 11,559/sq.ft.      1
₹ 11,497/sq.ft.      1
₹ 13,984/sq.ft.      1
₹ 16,445/sq.ft.      1
₹ 8,040/sq.ft.       1
₹ 7,262/sq.ft.       1
₹ 5,958/sq.ft.       1
₹ 5,952/sq.ft.       1
₹ 6,562/sq.ft.       1
₹ 11,442/sq.ft.      1
₹ 6,435/sq.ft.       1
₹ 9,912/sq.ft.       1
₹ 8,802/sq.ft.       1
₹ 10,482/sq.ft.      1
₹ 4,106/sq.ft.       1
₹ 8,982/sq.ft.       1
₹ 9,519/sq.ft.       1
₹ 8,734/sq.ft.       1
₹ 12,272/sq.ft.      1
₹ 8,700/sq.ft.       1
₹ 15,560/sq.ft.      1
₹ 5,413/sq.ft.       1
₹ 7,453/sq.ft.       1
₹ 4,778/sq.ft.       1
₹ 7,769/sq.ft.       1
₹ 7,103/sq.ft.       1
₹ 12,009/sq.ft.      1
₹ 3,664/sq.ft.       1
₹ 3,650/sq.ft.       1
₹ 11,209/sq.ft.      1
₹ 6,768/sq.ft.       1
₹ 7,010/sq.ft.       1
₹ 7,171/sq.ft.       1
₹ 5,720/sq.ft.       1
₹ 6,556/sq.ft.       1
₹ 5,265/sq.ft.       1
₹ 7,891/sq.ft.       1
₹ 4,404/sq.ft.       1
₹ 2,666/sq.ft.       1
₹ 2,051/sq.ft.       1
₹ 6,914/sq.ft.       1
₹ 6,601/sq.ft.       1
₹ 11,725/sq.ft.      1
₹ 10,418/sq.ft.      1
₹ 9,218/sq.ft.       1
₹ 7,760/sq.ft.       1
₹ 10,375/sq.ft.      1
₹ 9,371/sq.ft.       1
₹ 6,926/sq.ft.       1
₹ 10,491/sq.ft.      1
₹ 5,571/sq.ft.       1
₹ 11,190/sq.ft.      1
₹ 11,920/sq.ft.      1
₹ 6,870/sq.ft.       1
₹ 11,600/sq.ft.      1
₹ 7,402/sq.ft.       1
₹ 11,963/sq.ft.      1
₹ 4,868/sq.ft.       1
₹ 5,625/sq.ft.       1
₹ 7,882/sq.ft.       1
₹ 6,137/sq.ft.       1
₹ 10,058/sq.ft.      1
₹ 4,458/sq.ft.       1
₹ 9,016/sq.ft.       1
₹ 4,931/sq.ft.       1
₹ 8,387/sq.ft.       1
₹ 14,838/sq.ft.      1
₹ 10,697/sq.ft.      1
₹ 13,177/sq.ft.      1
₹ 6,587/sq.ft.       1
₹ 8,446/sq.ft.       1
₹ 6,552/sq.ft.       1
₹ 6,478/sq.ft.       1
₹ 9,236/sq.ft.       1
₹ 4,694/sq.ft.       1
₹ 4,591/sq.ft.       1
₹ 14,652/sq.ft.      1
₹ 3,692/sq.ft.       1
₹ 6,185/sq.ft.       1
₹ 5,719/sq.ft.       1
₹ 5,220/sq.ft.       1
₹ 14,009/sq.ft.      1
₹ 5,039/sq.ft.       1
₹ 4,325/sq.ft.       1
₹ 5,013/sq.ft.       1
₹ 19,444/sq.ft.      1
₹ 5,666/sq.ft.       1
₹ 4,453/sq.ft.       1
₹ 7,422/sq.ft.       1
₹ 8,515/sq.ft.       1
₹ 3,600/sq.ft.       1
₹ 4,977/sq.ft.       1
₹ 5,861/sq.ft.       1
₹ 5,476/sq.ft.       1
₹ 6,340/sq.ft.       1
₹ 5,245/sq.ft.       1
₹ 7,299/sq.ft.       1
₹ 3,158/sq.ft.       1
₹ 6,598/sq.ft.       1
₹ 5,777/sq.ft.       1
₹ 8,990/sq.ft.       1
₹ 4,512/sq.ft.       1
₹ 12,408/sq.ft.      1
₹ 4,470/sq.ft.       1
₹ 14,551/sq.ft.      1
₹ 6,526/sq.ft.       1
₹ 15,267/sq.ft.      1
₹ 2,638/sq.ft.       1
₹ 5,583/sq.ft.       1

In [3]:
df = pd.read_csv('work_till_22_09.csv')

In [4]:
df.head(5)

,Unnamed: 0,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [6]:
df = df.drop('Unnamed: 0', axis=1)

In [7]:
df.head(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [8]:
df['price'].isnull().sum()

21

In [9]:
df['price_per_sqft']

0         ₹ 5,000/sq.ft.
1         ₹ 7,692/sq.ft.
2         ₹ 6,722/sq.ft.
3        ₹ 12,250/sq.ft.
4         ₹ 5,204/sq.ft.
5         ₹ 6,269/sq.ft.
6        ₹ 13,333/sq.ft.
7         ₹ 7,860/sq.ft.
8         ₹ 8,148/sq.ft.
9        ₹ 16,885/sq.ft.
10        ₹ 9,767/sq.ft.
11        ₹ 5,587/sq.ft.
12        ₹ 6,940/sq.ft.
13        ₹ 6,859/sq.ft.
14        ₹ 5,384/sq.ft.
15       ₹ 16,859/sq.ft.
16       ₹ 14,084/sq.ft.
17       ₹ 11,475/sq.ft.
18                   NaN
19       ₹ 10,476/sq.ft.
20        ₹ 9,156/sq.ft.
21        ₹ 8,604/sq.ft.
22        ₹ 7,796/sq.ft.
23        ₹ 9,135/sq.ft.
24       ₹ 12,855/sq.ft.
25        ₹ 7,910/sq.ft.
26       ₹ 18,331/sq.ft.
27       ₹ 24,300/sq.ft.
28        ₹ 5,600/sq.ft.
29       ₹ 12,784/sq.ft.
30       ₹ 26,936/sq.ft.
31       ₹ 10,156/sq.ft.
32        ₹ 7,194/sq.ft.
33        ₹ 6,538/sq.ft.
34        ₹ 5,769/sq.ft.
35        ₹ 6,950/sq.ft.
36        ₹ 8,866/sq.ft.
37        ₹ 5,403/sq.ft.
38        ₹ 5,714/sq.ft.
39       ₹ 15,151/sq.ft.
40        ₹ 6,200/sq.ft.
41       ₹ 16,000/sq.ft.
42        ₹ 6,378/sq.ft.
43        ₹ 3,571/sq.ft.
44        ₹ 7,846/sq.ft.
45        ₹ 7,297/sq.ft.
46        ₹ 7,581/sq.ft.
47       ₹ 10,005/sq.ft.
48       ₹ 10,714/sq.ft.
49       ₹ 16,969/sq.ft.
50       ₹ 14,545/sq.ft.
51        ₹ 5,424/sq.ft.
52        ₹ 7,410/sq.ft.
53        ₹ 6,400/sq.ft.
54        ₹ 4,715/sq.ft.
55        ₹ 5,000/sq.ft.
56        ₹ 6,666/sq.ft.
57        ₹ 9,872/sq.ft.
58        ₹ 6,594/sq.ft.
59        ₹ 5,555/sq.ft.
60        ₹ 7,000/sq.ft.
61        ₹ 5,007/sq.ft.
62        ₹ 7,857/sq.ft.
63        ₹ 6,376/sq.ft.
64        ₹ 8,863/sq.ft.
65        ₹ 4,320/sq.ft.
66       ₹ 11,111/sq.ft.
67       ₹ 10,410/sq.ft.
68        ₹ 5,178/sq.ft.
69        ₹ 5,556/sq.ft.
70        ₹ 4,744/sq.ft.
71        ₹ 9,406/sq.ft.
72        ₹ 5,521/sq.ft.
73        ₹ 6,404/sq.ft.
74        ₹ 8,432/sq.ft.
75        ₹ 4,687/sq.ft.
76        ₹ 6,812/sq.ft.
77       ₹ 12,505/sq.ft.
78        ₹ 5,128/sq.ft.
79       ₹ 11,153/sq.ft.
80        ₹ 8,784/sq.ft.
81           ₹ 79/sq.ft.
82       ₹ 10,599/sq.ft.
83        ₹ 6,500/sq.ft.
84        ₹ 3,768/sq.ft.
85       ₹ 17,200/sq.ft.
86        ₹ 6,338/sq.ft.
87        ₹ 6,615/sq.ft.
88        ₹ 3,166/sq.ft.
89        ₹ 9,838/sq.ft.
90       ₹ 13,957/sq.ft.
91        ₹ 8,035/sq.ft.
92        ₹ 8,036/sq.ft.
93        ₹ 8,768/sq.ft.
94        ₹ 8,611/sq.ft.
95        ₹ 6,600/sq.ft.
96       ₹ 11,738/sq.ft.
97       ₹ 14,492/sq.ft.
98       ₹ 12,800/sq.ft.
99        ₹ 7,800/sq.ft.
100      ₹ 15,590/sq.ft.
101       ₹ 5,641/sq.ft.
102      ₹ 13,750/sq.ft.
103       ₹ 7,407/sq.ft.
104      ₹ 10,500/sq.ft.
105       ₹ 9,849/sq.ft.
106      ₹ 11,482/sq.ft.
107       ₹ 4,500/sq.ft.
108      ₹ 17,617/sq.ft.
109       ₹ 6,106/sq.ft.
110       ₹ 7,739/sq.ft.
111      ₹ 10,018/sq.ft.
112      ₹ 16,030/sq.ft.
113           ₹ 7/sq.ft.
114       ₹ 5,600/sq.ft.
115       ₹ 9,955/sq.ft.
116       ₹ 9,027/sq.ft.
117      ₹ 10,589/sq.ft.
118       ₹ 6,443/sq.ft.
119       ₹ 7,407/sq.ft.
120       ₹ 6,420/sq.ft.
121       ₹ 5,405/sq.ft.
122       ₹ 8,784/sq.ft.
123      ₹ 12,744/sq.ft.
124       ₹ 9,285/sq.ft.
125       ₹ 8,000/sq.ft.
126      ₹ 11,755/sq.ft.
127      ₹ 11,755/sq.ft.
128       ₹ 7,149/sq.ft.
129       ₹ 9,146/sq.ft.
130      ₹ 13,115/sq.ft.
131       ₹ 7,396/sq.ft.
132       ₹ 5,397/sq.ft.
133       ₹ 7,909/sq.ft.
134      ₹ 12,920/sq.ft.
135       ₹ 4,615/sq.ft.
136       ₹ 7,106/sq.ft.
137       ₹ 7,692/sq.ft.
138       ₹ 5,883/sq.ft.
139       ₹ 6,806/sq.ft.
140       ₹ 9,502/sq.ft.
141       ₹ 6,200/sq.ft.
142       ₹ 6,700/sq.ft.
143       ₹ 5,750/sq.ft.
144      ₹ 12,526/sq.ft.
145      ₹ 12,244/sq.ft.
146       ₹ 7,424/sq.ft.
147      ₹ 10,361/sq.ft.
148       ₹ 6,470/sq.ft.
149      ₹ 13,600/sq.ft.
150       ₹ 5,308/sq.ft.
151       ₹ 5,556/sq.ft.
152       ₹ 4,500/sq.ft.
153       ₹ 4,666/sq.ft.
154      ₹ 14,444/sq.ft.
155       ₹ 7,188/sq.ft.
156      ₹ 10,828/sq.ft.
157       ₹ 6,111/sq.ft.
158       ₹ 9,615/sq.ft.
159      ₹ 15,000/sq.ft.
160      ₹ 15,664/sq.ft.
161      ₹ 13,496/sq.ft.
162       ₹ 9,463/sq.ft.
163       ₹ 7,782/sq.ft.
164       ₹ 7,780/sq.ft.
165       ₹ 8,043/sq.ft.
166       ₹ 6,578/sq.ft.
167       ₹ 7,963/sq.ft.
168       ₹ 6,593/sq.ft.
169      ₹ 12,185/sq.ft.
170       ₹ 6,789/sq.ft.
171       ₹ 7,500/sq.ft.
172       ₹ 7,444/sq.ft.
173       ₹ 8,108/sq.ft.
174       ₹ 6,345/sq.ft.
175       ₹ 6,967/sq.ft.
176       ₹ 6,250/sq.ft.
177       ₹ 7,627/sq.ft.
178       ₹ 6,703/sq.ft.
179       ₹ 6,506/sq.ft.
180       ₹ 6,150/sq.ft.
181       ₹ 8,928/sq.ft.
182      ₹ 12,106/sq.ft.
183      ₹ 13,074/sq.ft.
184       ₹ 8,081/sq.ft.
185      ₹ 13,136/sq.ft.
186      ₹ 10,139/sq.ft.
187       ₹ 4,731/sq.ft.
188       ₹ 5,142/sq.ft.
189       ₹ 4,258/sq.ft.
190       ₹ 7,496/sq.ft.
191      ₹ 17,441/sq.ft.
192      ₹ 12,619/sq.ft.
193       ₹ 4,546/sq.ft.
194      ₹ 10,000/sq.ft.
195       ₹ 9,904/sq.ft.
196      ₹ 15,003/sq.ft.
197       ₹ 3,970/sq.ft.
198       ₹ 5,067/sq.ft.
199      ₹ 12,500/sq.ft.
200       ₹ 4,105/sq.ft.
201       ₹ 6,667/sq.ft.
202       ₹ 8,504/sq.ft.
203      ₹ 14,118/sq.ft.
204       ₹ 8,450/sq.ft.
205       ₹ 2,700/sq.ft.
206       ₹ 8,886/sq.ft.
207      ₹ 18,492/sq.ft.
208       ₹ 7,643/sq.ft.
209       ₹ 9,166/sq.ft.
210      ₹ 16,923/sq.ft.
211       ₹ 3,975/sq.ft.
212       ₹ 4,705/sq.ft.
213       ₹ 6,225/sq.ft.
214      ₹ 10,000/sq.ft.
215       ₹ 6,542/sq.ft.
216      ₹ 18,000/sq.ft.
217      ₹ 17,990/sq.ft.
218       ₹ 7,500/sq.ft.
219      ₹ 17,997/sq.ft.
220      ₹ 18,477/sq.ft.
221      ₹ 14,168/sq.ft.
222      ₹ 11,724/sq.ft.
223       ₹ 7,272/sq.ft.
224       ₹ 7,036/sq.ft.
225       ₹ 4,105/sq.ft.
226       ₹ 6,790/sq.ft.
227       ₹ 5,420/sq.ft.
228       ₹ 6,024/sq.ft.
229       ₹ 5,882/sq.ft.
230      ₹ 11,716/sq.ft.
231      ₹ 12,181/sq.ft.
232      ₹ 12,250/sq.ft.
233       ₹ 7,455/sq.ft.
234      ₹ 13,500/sq.ft.
235       ₹ 9,909/sq.ft.
236       ₹ 9,876/sq.ft.
237       ₹ 5,000/sq.ft.
238       ₹ 4,820/sq.ft.
239       ₹ 7,032/sq.ft.
240       ₹ 5,548/sq.ft.
241       ₹ 5,888/sq.ft.
242       ₹ 7,585/sq.ft.
243       ₹ 6,734/sq.ft.
244       ₹ 9,024/sq.ft.
245       ₹ 8,000/sq.ft.
246       ₹ 9,166/sq.ft.
247      ₹ 15,980/sq.ft.
248      ₹ 10,601/sq.ft.
249      ₹ 28,000/sq.ft.
250       ₹ 4,444/sq.ft.
251      ₹ 14,335/sq.ft.
252      ₹ 15,793/sq.ft.
253      ₹ 12,500/sq.ft.
254      ₹ 26,562/sq.ft.
255       ₹ 5,000/sq.ft.
256       ₹ 6,300/sq.ft.
257       ₹ 7,777/sq.ft.
258      ₹ 14,100/sq.ft.
259       ₹ 6,983/sq.ft.
260       ₹ 5,892/sq.ft.
261      ₹ 10,158/sq.ft.
262      ₹ 13,750/sq.ft.
263       ₹ 3,648/sq.ft.
264       ₹ 7,772/sq.ft.
265       ₹ 6,739/sq.ft.
266       ₹ 5,556/sq.ft.
267       ₹ 6,325/sq.ft.
268       ₹ 6,061/sq.ft.
269       ₹ 6,429/sq.ft.
270       ₹ 6,862/sq.ft.
271       ₹ 6,377/sq.ft.
272      ₹ 10,531/sq.ft.
273       ₹ 5,038/sq.ft.
274      ₹ 13,969/sq.ft.
275       ₹ 4,800/sq.ft.
276       ₹ 5,797/sq.ft.
277      ₹ 12,000/sq.ft.
278       ₹ 9,286/sq.ft.
279       ₹ 6,510/sq.ft.
280       ₹ 5,384/sq.ft.
281      ₹ 41,245/sq.ft.
282      ₹ 10,945/sq.ft.
283       ₹ 9,851/sq.ft.
284       ₹ 8,075/sq.ft.
285                 area
286      ₹ 13,269/sq.ft.
287       ₹ 7,727/sq.ft.
288      ₹ 15,998/sq.ft.
289       ₹ 7,865/sq.ft.
290       ₹ 7,400/sq.ft.
291       ₹ 7,510/sq.ft.
292       ₹ 8,514/sq.ft.
293       ₹ 4,599/sq.ft.
294      ₹ 13,000/sq.ft.
295      ₹ 14,257/sq.ft.
296       ₹ 9,333/sq.ft.
297      ₹ 14,214/sq.ft.
298      ₹ 14,110/sq.ft.
299       ₹ 7,248/sq.ft.
300       ₹ 6,921/sq.ft.
301      ₹ 10,603/sq.ft.
302       ₹ 8,620/sq.ft.
303       ₹ 9,090/sq.ft.
304       ₹ 7,391/sq.ft.
305       ₹ 4,666/sq.ft.
306      ₹ 16,960/sq.ft.
307      ₹ 33,209/sq.ft.
308      ₹ 11,516/sq.ft.
309      ₹ 14,202/sq.ft.
310       ₹ 8,181/sq.ft.
311      ₹ 10,500/sq.ft.
312       ₹ 6,666/sq.ft.
313      ₹ 11,500/sq.ft.
314       ₹ 9,900/sq.ft.
315      ₹ 17,619/sq.ft.
316      ₹ 17,000/sq.ft.
317       ₹ 8,206/sq.ft.
318      ₹ 15,240/sq.ft.
319       ₹ 7,727/sq.ft.
320      ₹ 15,998/sq.ft.
321       ₹ 7,865/sq.ft.
322       ₹ 7,400/sq.ft.
323      ₹ 13,000/sq.ft.
324      ₹ 14,257/sq.ft.
325      ₹ 14,214/sq.ft.
326       ₹ 7,248/sq.ft.
327       ₹ 6,921/sq.ft.
328      ₹ 10,603/sq.ft.
329       ₹ 8,620/sq.ft.
330       ₹ 9,090/sq.ft.
331       ₹ 7,391/sq.ft.
332       ₹ 4,666/sq.ft.
333      ₹ 16,960/sq.ft.
334      ₹ 11,516/sq.ft.
335       ₹ 8,181/sq.ft.
336       ₹ 6,666/sq.ft.
337       ₹ 9,900/sq.ft.
338      ₹ 17,619/sq.ft.
339       ₹ 8,206/sq.ft.
340      ₹ 19,363/sq.ft.
341       ₹ 5,832/sq.ft.
342       ₹ 9,777/sq.ft.
343       ₹ 6,542/sq.ft.
344       ₹ 8,160/sq.ft.
345       ₹ 9,334/sq.ft.
346       ₹ 9,473/sq.ft.
347       ₹ 6,597/sq.ft.
348       ₹ 5,897/sq.ft.
349      ₹ 18,181/sq.ft.
350       ₹ 4,271/sq.ft.
351       ₹ 7,725/sq.ft.
352      ₹ 10,895/sq.ft.
353      ₹ 11,845/sq.ft.
354      ₹ 23,401/sq.ft.
355       ₹ 9,182/sq.ft.
356      ₹ 12,782/sq.ft.
357      ₹ 15,681/sq.ft.
358       ₹ 7,539/sq.ft.
359       ₹ 8,072/sq.ft.
360      ₹ 14,376/sq.ft.
361       ₹ 9,221/sq.ft.
362       ₹ 8,606/sq.ft.
363      ₹ 10,000/sq.ft.
364      ₹ 14,516/sq.ft.
365      ₹ 14,583/sq.ft.
366      ₹ 19,200/sq.ft.
367       ₹ 8,047/sq.ft.
368       ₹ 4,888/sq.ft.
369      ₹ 10,007/sq.ft.
370      ₹ 13,765/sq.ft.
371      ₹ 14,478/sq.ft.
372       ₹ 4,651/sq.ft.
373       ₹ 9,740/sq.ft.
374       ₹ 9,552/sq.ft.
375      ₹ 14,800/sq.ft.
376      ₹ 18,571/sq.ft.
377      ₹ 14,500/sq.ft.
378       ₹ 8,604/sq.ft.
379       ₹ 8,521/sq.ft.
380       ₹ 6,509/sq.ft.
381      ₹ 11,028/sq.ft.
382       ₹ 6,134/sq.ft.
383      ₹ 11,426/sq.ft.
384      ₹ 11,938/sq.ft.
385      ₹ 13,281/sq.ft.
386      ₹ 12,318/sq.ft.
387       ₹ 8,510/sq.ft.
388      ₹ 12,810/sq.ft.
389       ₹ 7,825/sq.ft.
390       ₹ 7,825/sq.ft.
391      ₹ 14,938/sq.ft.
392       ₹ 6,709/sq.ft.
393      ₹ 10,769/sq.ft.
394       ₹ 8,087/sq.ft.
395       ₹ 8,181/sq.ft.
396      ₹ 10,378/sq.ft.
397      ₹ 13,696/sq.ft.
398       ₹ 8,043/sq.ft.
399      ₹ 10,000/sq.ft.
400       ₹ 7,267/sq.ft.
401      ₹ 11,832/sq.ft.
402      ₹ 14,254/sq.ft.
403      ₹ 11,903/sq.ft.
404      ₹ 13,224/sq.ft.
405      ₹ 12,000/sq.ft.
406      ₹ 13,636/sq.ft.
407      ₹ 14,242/sq.ft.
408       ₹ 5,681/sq.ft.
409       ₹ 4,881/sq.ft.
410       ₹ 4,259/sq.ft.
411      ₹ 11,185/sq.ft.
412      ₹ 15,575/sq.ft.
413       ₹ 7,804/sq.ft.
414       ₹ 9,895/sq.ft.
415       ₹ 7,884/sq.ft.
416      ₹ 17,455/sq.ft.
417      ₹ 17,777/sq.ft.
418       ₹ 7,272/sq.ft.
419      ₹ 13,383/sq.ft.
420      ₹ 12,312/sq.ft.
421      ₹ 11,584/sq.ft.
422       ₹ 5,011/sq.ft.
423      ₹ 13,266/sq.ft.
424      ₹ 11,505/sq.ft.
425       ₹ 7,600/sq.ft.
426      ₹ 15,384/sq.ft.
427       ₹ 9,490/sq.ft.
428       ₹ 9,558/sq.ft.
429      ₹ 28,266/sq.ft.
430      ₹ 13,750/sq.ft.
431       ₹ 7,869/sq.ft.
432      ₹ 13,495/sq.ft.
433      ₹ 18,400/sq.ft.
434       ₹ 8,484/sq.ft.
435      ₹ 17,721/sq.ft.
436       ₹ 5,530/sq.ft.
437      ₹ 16,060/sq.ft.
438      ₹ 12,346/sq.ft.
439       ₹ 7,674/sq.ft.
440       ₹ 6,921/sq.ft.
441      ₹ 14,871/sq.ft.
442       ₹ 9,473/sq.ft.
443      ₹ 11,121/sq.ft.
444      ₹ 14,242/sq.ft.
445      ₹ 16,486/sq.ft.
446       ₹ 8,410/sq.ft.
447      ₹ 16,969/sq.ft.
448      ₹ 21,360/sq.ft.
449      ₹ 14,583/sq.ft.
450      ₹ 26,790/sq.ft.
451      ₹ 12,500/sq.ft.
452      ₹ 10,516/sq.ft.
453      ₹ 10,936/sq.ft.
454       ₹ 7,945/sq.ft.
455       ₹ 7,220/sq.ft.
456      ₹ 12,627/sq.ft.
457       ₹ 7,392/sq.ft.
458       ₹ 6,049/sq.ft.
459      ₹ 12,818/sq.ft.
460      ₹ 16,050/sq.ft.
461      ₹ 18,500/sq.ft.
462       ₹ 5,505/sq.ft.
463       ₹ 7,541/sq.ft.
464       ₹ 9,000/sq.ft.
465       ₹ 7,541/sq.ft.
466       ₹ 6,679/sq.ft.
467       ₹ 6,597/sq.ft.
468      ₹ 13,125/sq.ft.
469       ₹ 5,788/sq.ft.
470      ₹ 13,690/sq.ft.
471       ₹ 8,051/sq.ft.
472       ₹ 6,141/sq.ft.
473      ₹ 28,101/sq.ft.
474       ₹ 8,080/sq.ft.
475       ₹ 7,260/sq.ft.
476       ₹ 8,376/sq.ft.
477      ₹ 14,950/sq.ft.
478       ₹ 9,783/sq.ft.
479      ₹ 12,544/sq.ft.
480       ₹ 7,150/sq.ft.
481      ₹ 12,235/sq.ft.
482      ₹ 14,418/sq.ft.
483      ₹ 14,079/sq.ft.
484       ₹ 6,713/sq.ft.
485      ₹ 13,790/sq.ft.
486      ₹ 10,814/sq.ft.
487      ₹ 12,140/sq.ft.
488      ₹ 15,160/sq.ft.
489       ₹ 7,610/sq.ft.
490       ₹ 6,661/sq.ft.
491       ₹ 7,780/sq.ft.
492       ₹ 6,163/sq.ft.
493       ₹ 7,350/sq.ft.
494      ₹ 10,901/sq.ft.
495       ₹ 8,163/sq.ft.
496       ₹ 6,000/sq.ft.
497       ₹ 4,193/sq.ft.
498       ₹ 3,309/sq.ft.
499      ₹ 15,906/sq.ft.
500      ₹ 11,294/sq.ft.
501      ₹ 11,204/sq.ft.
502       ₹ 8,484/sq.ft.
503      ₹ 11,470/sq.ft.
504      ₹ 10,567/sq.ft.
505      ₹ 10,000/sq.ft.
506      ₹ 12,788/sq.ft.
507      ₹ 13,076/sq.ft.
508       ₹ 6,987/sq.ft.
509       ₹ 6,826/sq.ft.
510       ₹ 9,528/sq.ft.
511      ₹ 15,514/sq.ft.
512      ₹ 14,563/sq.ft.
513       ₹ 9,212/sq.ft.
514       ₹ 6,888/sq.ft.
515      ₹ 11,412/sq.ft.
516      ₹ 11,174/sq.ft.
517      ₹ 10,841/sq.ft.
518       ₹ 4,857/sq.ft.
519      ₹ 10,936/sq.ft.
520       ₹ 5,717/sq.ft.
521      ₹ 10,000/sq.ft.
522       ₹ 5,867/sq.ft.
523      ₹ 14,177/sq.ft.
524      ₹ 10,174/sq.ft.
525       ₹ 7,646/sq.ft.
526       ₹ 6,961/sq.ft.
527       ₹ 8,632/sq.ft.
528       ₹ 7,586/sq.ft.
529       ₹ 4,528/sq.ft.
530       ₹ 8,580/sq.ft.
531       ₹ 5,513/sq.ft.
532       ₹ 6,666/sq.ft.
533      ₹ 15,384/sq.ft.
534       ₹ 9,210/sq.ft.
535       ₹ 9,210/sq.ft.
536      ₹ 13,571/sq.ft.
537      ₹ 11,686/sq.ft.
538       ₹ 8,036/sq.ft.
539       ₹ 6,585/sq.ft.
540       ₹ 7,230/sq.ft.
541       ₹ 6,453/sq.ft.
542       ₹ 6,578/sq.ft.
543       ₹ 5,973/sq.ft.
544       ₹ 5,896/sq.ft.
545      ₹ 15,185/sq.ft.
546      ₹ 12,152/sq.ft.
547      ₹ 13,253/sq.ft.
548      ₹ 12,190/sq.ft.
549       ₹ 4,370/sq.ft.
550       ₹ 4,355/sq.ft.
551       ₹ 8,461/sq.ft.
552       ₹ 8,834/sq.ft.
553       ₹ 7,734/sq.ft.
554       ₹ 5,418/sq.ft.
555      ₹ 11,358/sq.ft.
556      ₹ 12,599/sq.ft.
557       ₹ 6,313/sq.ft.
558      ₹ 13,678/sq.ft.
559      ₹ 19,747/sq.ft.
560       ₹ 7,878/sq.ft.
561       ₹ 5,004/sq.ft.
562       ₹ 4,836/sq.ft.
563       ₹ 9,105/sq.ft.
564      ₹ 10,595/sq.ft.
565       ₹ 8,646/sq.ft.
566      ₹ 10,461/sq.ft.
567      ₹ 10,080/sq.ft.
568      ₹ 10,699/sq.ft.
569       ₹ 8,172/sq.ft.
570      ₹ 12,571/sq.ft.
571       ₹ 7,608/sq.ft.
572      ₹ 11,914/sq.ft.
573      ₹ 14,983/sq.ft.
574       ₹ 8,759/sq.ft.
575       ₹ 6,655/sq.ft.
576       ₹ 5,521/sq.ft.
577       ₹ 5,674/sq.ft.
578       ₹ 8,839/sq.ft.
579       ₹ 7,948/sq.ft.
580       ₹ 8,035/sq.ft.
581      ₹ 16,750/sq.ft.
582      ₹ 16,470/sq.ft.
583      ₹ 16,580/sq.ft.
584       ₹ 8,108/sq.ft.
585      ₹ 10,334/sq.ft.
586       ₹ 9,266/sq.ft.
587      ₹ 11,860/sq.ft.
588       ₹ 7,812/sq.ft.
589       ₹ 8,947/sq.ft.
590       ₹ 9,051/sq.ft.
591       ₹ 9,622/sq.ft.
592       ₹ 7,142/sq.ft.
593      ₹ 13,528/sq.ft.
594       ₹ 5,683/sq.ft.
595       ₹ 6,476/sq.ft.
596       ₹ 4,864/sq.ft.
597       ₹ 5,499/sq.ft.
598       ₹ 7,449/sq.ft.
599       ₹ 7,065/sq.ft.
600       ₹ 9,980/sq.ft.
601       ₹ 9,036/sq.ft.
602      ₹ 13,888/sq.ft.
603      ₹ 13,878/sq.ft.
604      ₹ 14,557/sq.ft.
605      ₹ 12,325/sq.ft.
606       ₹ 9,133/sq.ft.
607       ₹ 7,750/sq.ft.
608      ₹ 13,281/sq.ft.
609       ₹ 6,819/sq.ft.
610      ₹ 17,285/sq.ft.
611       ₹ 8,834/sq.ft.
612      ₹ 18,518/sq.ft.
613       ₹ 5,500/sq.ft.
614       ₹ 7,150/sq.ft.
615      ₹ 12,222/sq.ft.
616      ₹ 13,929/sq.ft.
617      ₹ 12,500/sq.ft.
618       ₹ 6,514/sq.ft.
619       ₹ 6,580/sq.ft.
620       ₹ 6,708/sq.ft.
621      ₹ 13,846/sq.ft.
622       ₹ 5,878/sq.ft.
623       ₹ 9,909/sq.ft.
624      ₹ 13,875/sq.ft.
625      ₹ 12,400/sq.ft.
626       ₹ 7,146/sq.ft.
627      ₹ 14,074/sq.ft.
628      ₹ 11,739/sq.ft.
629      ₹ 10,596/sq.ft.
630       ₹ 7,014/sq.ft.
631       ₹ 8,139/sq.ft.
632       ₹ 5,825/sq.ft.
633      ₹ 12,110/sq.ft.
634      ₹ 14,623/sq.ft.
635       ₹ 6,523/sq.ft.
636       ₹ 8,100/sq.ft.
637      ₹ 21,013/sq.ft.
638       ₹ 7,437/sq.ft.
639      ₹ 11,666/sq.ft.
640       ₹ 6,455/sq.ft.
641       ₹ 4,022/sq.ft.
642       ₹ 3,935/sq.ft.
643       ₹ 9,387/sq.ft.
644       ₹ 9,117/sq.ft.
645      ₹ 10,953/sq.ft.
646      ₹ 11,052/sq.ft.
647      ₹ 14,536/sq.ft.
648      ₹ 12,127/sq.ft.
649      ₹ 12,144/sq.ft.
650      ₹ 10,994/sq.ft.
651      ₹ 10,761/sq.ft.
652      ₹ 15,469/sq.ft.
653       ₹ 8,333/sq.ft.
654      ₹ 13,392/sq.ft.
655      ₹ 20,533/sq.ft.
656      ₹ 24,211/sq.ft.
657       ₹ 5,588/sq.ft.
658       ₹ 8,389/sq.ft.
659       ₹ 8,474/sq.ft.
660       ₹ 8,724/sq.ft.
661       ₹ 8,750/sq.ft.
662       ₹ 6,250/sq.ft.
663       ₹ 9,128/sq.ft.
664       ₹ 7,496/sq.ft.
665       ₹ 7,857/sq.ft.
666       ₹ 6,953/sq.ft.
667      ₹ 13,750/sq.ft.
668      ₹ 11,574/sq.ft.
669      ₹ 11,505/sq.ft.
670      ₹ 13,725/sq.ft.
671       ₹ 6,215/sq.ft.
672       ₹ 4,814/sq.ft.
673       ₹ 7,500/sq.ft.
674      ₹ 35,483/sq.ft.
675       ₹ 7,403/sq.ft.
676       ₹ 7,223/sq.ft.
677      ₹ 17,484/sq.ft.
678      ₹ 12,169/sq.ft.
679       ₹ 8,242/sq.ft.
680      ₹ 10,365/sq.ft.
681       ₹ 7,789/sq.ft.
682      ₹ 13,343/sq.ft.
683      ₹ 14,068/sq.ft.
684       ₹ 5,859/sq.ft.
685       ₹ 5,820/sq.ft.
686       ₹ 5,660/sq.ft.
687       ₹ 6,254/sq.ft.
688       ₹ 4,531/sq.ft.
689      ₹ 10,178/sq.ft.
690       ₹ 9,203/sq.ft.
691      ₹ 15,007/sq.ft.
692       ₹ 9,090/sq.ft.
693      ₹ 10,028/sq.ft.
694       ₹ 8,516/sq.ft.
695       ₹ 6,060/sq.ft.
696       ₹ 6,825/sq.ft.
697      ₹ 14,987/sq.ft.
698       ₹ 6,647/sq.ft.
699       ₹ 6,052/sq.ft.
700      ₹ 14,090/sq.ft.
701       ₹ 9,642/sq.ft.
702       ₹ 8,679/sq.ft.
703      ₹ 14,727/sq.ft.
704      ₹ 14,418/sq.ft.
705      ₹ 13,671/sq.ft.
706      ₹ 10,262/sq.ft.
707      ₹ 10,224/sq.ft.
708      ₹ 11,694/sq.ft.
709       ₹ 9,850/sq.ft.
710       ₹ 7,641/sq.ft.
711       ₹ 8,825/sq.ft.
712       ₹ 6,029/sq.ft.
713      ₹ 10,545/sq.ft.
714       ₹ 8,204/sq.ft.
715      ₹ 13,758/sq.ft.
716      ₹ 15,685/sq.ft.
717       ₹ 6,286/sq.ft.
718       ₹ 6,846/sq.ft.
719       ₹ 6,002/sq.ft.
720       ₹ 7,751/sq.ft.
721       ₹ 8,062/sq.ft.
722       ₹ 5,725/sq.ft.
723       ₹ 5,930/sq.ft.
724       ₹ 9,238/sq.ft.
725       ₹ 5,856/sq.ft.
726      ₹ 14,179/sq.ft.
727       ₹ 6,470/sq.ft.
728       ₹ 7,096/sq.ft.
729       ₹ 9,433/sq.ft.
730       ₹ 8,998/sq.ft.
731      ₹ 11,451/sq.ft.
732      ₹ 10,651/sq.ft.
733       ₹ 6,242/sq.ft.
734       ₹ 5,490/sq.ft.
735       ₹ 8,922/sq.ft.
736       ₹ 6,310/sq.ft.
737      ₹ 10,162/sq.ft.
738       ₹ 7,116/sq.ft.
739       ₹ 6,655/sq.ft.
740       ₹ 6,265/sq.ft.
741       ₹ 5,808/sq.ft.
742       ₹ 4,080/sq.ft.
743      ₹ 10,237/sq.ft.
744       ₹ 8,611/sq.ft.
745       ₹ 9,822/sq.ft.
746       ₹ 6,000/sq.ft.
747       ₹ 4,308/sq.ft.
748       ₹ 3,953/sq.ft.
749      ₹ 12,484/sq.ft.
750      ₹ 15,531/sq.ft.
751       ₹ 5,762/sq.ft.
752       ₹ 6,852/sq.ft.
753       ₹ 7,641/sq.ft.
754      ₹ 14,418/sq.ft.
755      ₹ 14,843/sq.ft.
756      ₹ 12,846/sq.ft.
757      ₹ 20,388/sq.ft.
758      ₹ 13,580/sq.ft.
759       ₹ 4,500/sq.ft.
760       ₹ 7,750/sq.ft.
761      ₹ 12,658/sq.ft.
762      ₹ 16,266/sq.ft.
763      ₹ 21,577/sq.ft.
764      ₹ 13,636/sq.ft.
765       ₹ 7,179/sq.ft.
766      ₹ 13,383/sq.ft.
767       ₹ 7,641/sq.ft.
768      ₹ 11,713/sq.ft.
769      ₹ 12,444/sq.ft.
770      ₹ 10,714/sq.ft.
771       ₹ 8,270/sq.ft.
772      ₹ 11,218/sq.ft.
773       ₹ 7,525/sq.ft.
774       ₹ 6,801/sq.ft.
775       ₹ 6,692/sq.ft.
776       ₹ 7,590/sq.ft.
777      ₹ 19,174/sq.ft.
778       ₹ 5,207/sq.ft.
779       ₹ 5,252/sq.ft.
780       ₹ 8,875/sq.ft.
781      ₹ 16,666/sq.ft.
782       ₹ 8,916/sq.ft.
783      ₹ 13,928/sq.ft.
784       ₹ 5,597/sq.ft.
785       ₹ 7,850/sq.ft.
786       ₹ 7,817/sq.ft.
787       ₹ 8,395/sq.ft.
788       ₹ 8,532/sq.ft.
789      ₹ 10,037/sq.ft.
790       ₹ 6,049/sq.ft.
791       ₹ 5,942/sq.ft.
792       ₹ 6,476/sq.ft.
793      ₹ 10,727/sq.ft.
794       ₹ 9,565/sq.ft.
795       ₹ 6,227/sq.ft.
796      ₹ 10,147/sq.ft.
797      ₹ 10,529/sq.ft.
798      ₹ 12,372/sq.ft.
799      ₹ 11,817/sq.ft.

In [25]:
import re
def clean_price(price):
    if pd.isna(price):
        return None 
    
    match = re.search(r'₹\s?([\d,]+)/sq\.ft\.', price)
    if match:
        return float(match.group(1).replace(',',''))
    return None

In [12]:
df_price = df.copy()

In [29]:
df['price_per_sqft'] = df['price_per_sqft'].apply(clean_price)

In [30]:
df.head(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [3]:
df = pd.read_csv('work_till_25092024')

In [4]:
df.head(2)

,Unnamed: 0,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [5]:
df = df.drop('Unnamed: 0', axis=1)

In [6]:
df.head(2)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [9]:
df.to_csv('worktill250920241.csv')

In [11]:
#Bedroom

df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
bedRoom          1
Name: count, dtype: int64

In [16]:
df[df['bedRoom'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2842,2 BHK Flat in Sector 107 Gurgaon,signature global solera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2843,4 BHK Flat in Sector 53 Gurgaon,tulip monsella,NaN,33198.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2844,2 BHK Flat in New Palam Vihar,my home,NaN,4400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2845,2 BHK Flat in Sohna,breez global hill view,NaN,5470.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2915,3 BHK Flat in Sector 99A Gurgaon,pareena coban residences,NaN,5759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2916,1 BHK Flat in Golf Course Ext Road,ikon tower baani city centre,NaN,12437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2917,2 BHK Flat in Sector 89 Gurgaon,greenopolis,NaN,4820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2919,4 BHK Flat in C Block Sushant Lok Phase 1,maple heights,NaN,8888.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2920,2 BHK Flat in Sector 99 Gurgaon,assotech blith,NaN,6593.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2983,4 BHK Flat in DLF Phase 4,chanderlok society,NaN,7234.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2984,3 BHK Flat in Sector 9A Gurgaon,jammu and kashmir bank employees cghs,NaN,6129.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2985,3 BHK Flat in Sector 37C Gurgaon,ild greens,NaN,4723.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2986,3 BHK Flat in Adarsh Nagar,ss residency,NaN,4818.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2987,3 BHK Flat in Rajendra Park,uphar lakshya homes,NaN,4200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2988,2 BHK Flat in Sector 79 Gurgaon,supertech araville,NaN,9000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2989,3 BHK Flat in Sector 37C Gurgaon,corona optus,NaN,6361.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2990,3 BHK Flat in Sector 78 Gurgaon,umang monsoon breeze,NaN,6493.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2991,3 BHK Flat in Sector 88A Gurgaon,godrej oasis,NaN,8108.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2992,"2 BHK Flat in Godrej Aria , sector 79 , Gurgaon","godrej aria , sector 79 , gurgaon",NaN,11111.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df = df[~df['bedRoom'].isnull()]

In [18]:
df.head(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [22]:
df['bathroom'] = df['bathroom'].str.strip()

In [23]:
# Split on spaces and get the first element
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0)

In [30]:
df['bedRoom'] = pd.to_numeric(df['bedRoom'], errors='coerce')

In [31]:
df.head(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2.0,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2.0,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2.0,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2.0,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2.0,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [34]:
df['bedRoom'].isna().sum()

1

In [35]:
df['bedRoom'] = df['bedRoom'].fillna(0)

In [36]:
df['bedRoom'] = df['bedRoom'].astype('int')

In [37]:
df.head(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [39]:
# bathroom
df['bathroom'].value_counts()

bathroom
2 Bathrooms    1044
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
bathroom          1
Name: count, dtype: int64

In [40]:
df[df['bathroom']=='bathroom']

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
285,property_name,society,NaN,NaN,areaWithType,0,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating

In [45]:
# remove 285 column because it has no importance 

df.drop(285,axis=0, inplace= True)

In [47]:
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1461,3 BHK Flat in Sector 66 Gurgaon,emaar mgf the enclave,2.10,12352.0,Super Built up area 1920(178.37 sq.m.)Built Up...,3,4 Bathrooms,2 Balconies,Servant Room,"12022, Sector 66 Gurgaon, Gurgaon, Haryana",12nd of 16 Floors,North-East,1 to 5 Year Old,"['Emaar Colonnade', 'M3M Cosmopolitan', 'Elan ...","Situated in sector 66 gurgaon, emaar mgf the e...","['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '3 Ge...","['Water purifier', 'Centrally Air Conditioned'...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
2576,2 BHK Flat in Sector-33 Sohna,central park flower valley cerise floors,1.30,10743.0,Super Built up area 1210(112.41 sq.m.),2,2 Bathrooms,2 Balconies,Study Room,"G-136, Sector-33 Sohna, Gurgaon, Haryana",3rd of 4 Floors,North,Within 6 months,"['Sector 55-56, Sector 56', 'M3m 65th Avenue M...",It has a exclusive terrace area along with it,[],"['Lift(s)', 'Water Storage', 'Park', 'Visitor ...",NaN
1051,3 BHK Flat in Sector 70 Gurgaon,shree vardhman victoria,1.64,8410.0,Super Built up area 1950(181.16 sq.m.)Carpet a...,3,5 Bathrooms,3 Balconies,Servant Room,"803, Sector 70 Gurgaon, Gurgaon, Haryana",8th of 18 Floors,North-East,1 to 5 Year Old,"['Airia Mall', 'Golf Course Extn Road', 'Sohna...",Strategically located on southern peripheral r...,"['4 Fan', '5 Light', '4 AC', '1 Modular Kitche...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
2090,2 BHK Flat in Sohna,gls arawali homes,0.29,6035.0,Carpet area: 480.53 (44.64 sq.m.),2,2 Bathrooms,2 Balconies,NaN,"Sohna, Gurgaon, Haryana",9th of 13 Floors,East,1 to 5 Year Old,"['Huda City Centre', 'Golf Course Road', 'Delh...","Spacious rooms, east facing, fully ventilated ...",NaN,"['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Green Area5 out of 5', 'Construction4 out of..."
1036,3 BHK Flat in Sector 102 Gurgaon,emaar gurgaon greens,1.39,8424.0,Super Built up area 1650(153.29 sq.m.),3,3 Bathrooms,3 Balconies,Servant Room,"Sector 102 Gurgaon, Gurgaon, Haryana",7th of 14 Floors,West,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...","Situated in sector 102 gurgaon, emaar gurgaon ...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction4 out of..."

In [49]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0)

In [50]:
df.head(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [51]:
df['bathroom']= df['bathroom'].astype('int')

In [52]:
df['balcony'].value_counts()

balcony
3 Balconies     974
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [53]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [56]:
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1149,4 BHK Flat in Sector 72 Gurgaon,spaze privy,3.10,6692.0,Super Built up area 4632(430.33 sq.m.)Carpet a...,4,5,3+,"Servant Room,Pooja Room,Study Room,Store Room","Sector 72 Gurgaon, Gurgaon, Haryana",8th of 8 Floors,South,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Sohna road sector 72 it park spr road . Nh8 an...,"['8 Fan', '30 Light', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4 out of..."
68,2 BHK Flat in Sector 95 Gurgaon,ramsons kshitij,0.29,5178.0,Super Built up area 560(52.03 sq.m.),2,2,2,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",14th of 14 Floors,NaN,1 to 5 Year Old,"['Bangali Clinic', 'Yadav Clinic', 'Dr. J. S. ...",Residential apartment for sell.The property co...,[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area4 out of 5', 'Amenities4 out of 5'..."
2016,2 BHK Flat in Sector 63A Gurgaon,birla navya,2.10,16666.0,Carpet area: 1260 (117.06 sq.m.),2,2,2,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,2024-02-01 00:00:00,"['Sector 54 Chowk Metro Station', 'WorldMark G...",Premium floor residences at avik by birla navy...,"['2 Fan', '2 Geyser', '3 Light', '1 Modular Ki...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2004,3 BHK Flat in Sector 63A Gurgaon,birla navya,3.15,14632.0,Carpet area: 200,3,3,3,Others,"Sector 63A Gurgaon, Gurgaon, Haryana",4th of 4 Floors,East,2024-06-01 00:00:00,"['Sector 54 Chowk Metro Station', 'WorldMark G...",Only igbc gold certified luxury property.,"['1 Chimney', '3 AC', 'No Bed', 'No Curtains',...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
880,2 BHK Flat in Palam Vihar,bestech park view residency,0.98,6932.0,Super Built up area 1415(131.46 sq.m.),2,2,3,NaN,"Palam Vihar, Gurgaon, Haryana",11st of 14 Floors,East,5 to 10 Year Old,"['Dwarka Sector 21 Metro Station', 'HUDA Marke...",Bestech park view residency is one of gurgaon'...,"['2 Wardrobe', '4 Fan', '1 Geyser', '5 Light',...","['Security / Fire Alarm', 'Power Back-up', 'Li...","['Green Area5 out of 5', 'Construction4 out of..."

In [57]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Study Room,Pooja Room                              8
Servant Room,Study Room                            8
Study Room,Servant Room,Store Room                 7
Pooja Room,Store Room                              6
Pooja Room,Others                                  6
Others,Servant Room                                6
Servant Room,Study Room,Pooja Room,Store Room      6
Pooja Room,Servant Room,Others                     6
Study Room,Servant Room,Others                     5
Pooja Room,Store Room,Study Room,Servant Room      4
Pooja Room,Study Room,Store Room                   4
Servant Room,Pooja Room,Study Room,Store Room      3
Study Room,Pooja Room,Store Room                   3
Store Room,Servant Room                            3
Servant Room,Study Room,Store Room                 2
Pooja Room,Study Room,Others                       2
Study Room,Pooja Room,Servant Room                 2
Servant Room,Others,Store Room,Pooja Room          2
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Servant Room,Pooja Room,Study Room                 1
Servant Room,Study Room,Pooja Room                 1
Store Room,Pooja Room,Servant Room                 1
Servant Room,Pooja Room,Store Room,Study Room      1
Study Room,Store Room                              1
Store Room,Study Room                              1
Servant Room,Pooja Room,Store Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Study Room,Servant Room,Pooja Room                 1
Pooja Room,Servant Room,Study Room,Store Room      1
Pooja Room,Study Room,Store Room,Servant Room      1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [58]:
df['additionalRoom'].isnull().sum()

1305

In [59]:
df['additionalRoom'].fillna('not available', inplace =True )

In [60]:
df['additionalRoom'].value_counts()

additionalRoom
not available                                    1305
Servant Room                                      629
Study Room                                        232
Others                                            179
Pooja Room                                        132
Study Room,Servant Room                            81
Store Room                                         76
Pooja Room,Servant Room                            60
Servant Room,Others                                52
Servant Room,Pooja Room                            30
Study Room,Others                                  27
Pooja Room,Study Room,Servant Room,Others          25
Pooja Room,Study Room,Servant Room                 24
Servant Room,Store Room                            19
Pooja Room,Study Room                              13
Pooja Room,Study Room,Servant Room,Store Room      12
Study Room,Pooja Room                               8
Servant Room,Study Room                             8
Study Room,Servant Room,Store Room                  7
Pooja Room,Store Room                               6
Pooja Room,Others                                   6
Others,Servant Room                                 6
Servant Room,Study Room,Pooja Room,Store Room       6
Pooja Room,Servant Room,Others                      6
Study Room,Servant Room,Others                      5
Pooja Room,Store Room,Study Room,Servant Room       4
Pooja Room,Study Room,Store Room                    4
Servant Room,Pooja Room,Study Room,Store Room       3
Study Room,Pooja Room,Store Room                    3
Store Room,Servant Room                             3
Servant Room,Study Room,Store Room                  2
Pooja Room,Study Room,Others                        2
Study Room,Pooja Room,Servant Room                  2
Servant Room,Others,Store Room,Pooja Room           2
Servant Room,Others,Pooja Room                      2
Study Room,Servant Room,Pooja Room,Store Room       2
Others,Study Room                                   1
Servant Room,Study Room,Others                      1
Servant Room,Pooja Room,Study Room                  1
Servant Room,Study Room,Pooja Room                  1
Store Room,Pooja Room,Servant Room                  1
Servant Room,Pooja Room,Store Room,Study Room       1
Study Room,Store Room                               1
Store Room,Study Room                               1
Servant Room,Pooja Room,Store Room                  1
Study Room,Servant Room,Store Room,Pooja Room       1
Study Room,Servant Room,Pooja Room                  1
Pooja Room,Servant Room,Study Room,Store Room       1
Pooja Room,Study Room,Store Room,Servant Room       1
Store Room,Pooja Room                               1
Name: count, dtype: int64

In [61]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [64]:
df['additionalRoom'].value_counts().sum()

2997

In [65]:
# floorNum

df['floorNum']

0              4th   of 4 Floors
1              1st   of 3 Floors
2            12nd   of 14 Floors
3              2nd   of 4 Floors
4              5th   of 8 Floors
5              3rd   of 3 Floors
6             5th   of 25 Floors
7            14th   of 27 Floors
8              2nd   of 3 Floors
9            31st   of 40 Floors
10             1st   of 4 Floors
11            4th   of 13 Floors
12            4th   of 15 Floors
13            3rd   of 20 Floors
14           13rd   of 13 Floors
15           25th   of 25 Floors
16            Ground of 1 Floors
17           Ground of 14 Floors
18           11st   of 14 Floors
19           12nd   of 13 Floors
20             4th   of 4 Floors
21           11st   of 22 Floors
22             4th   of 4 Floors
23           Ground of 14 Floors
24           10th   of 25 Floors
25             3rd   of 3 Floors
26           20th   of 20 Floors
27            5th   of 17 Floors
28            4th   of 12 Floors
29             4th   of 4 Floors
30             1st   of 4 Floors
31           12nd   of 12 Floors
32            8th   of 12 Floors
33           20th   of 20 Floors
34             8th   of 8 Floors
35           21st   of 24 Floors
36           Ground of 11 Floors
37            6th   of 19 Floors
38            1st   of 19 Floors
39             1st   of 3 Floors
40           12nd   of 17 Floors
41            6th   of 24 Floors
42            1st   of 25 Floors
43             2nd   of 4 Floors
44             1st   of 4 Floors
45            9th   of 29 Floors
46             5th   of 8 Floors
47           18th   of 32 Floors
48           29th   of 31 Floors
49             3rd   of 5 Floors
50            3rd   of 26 Floors
51            5th   of 18 Floors
52             1st   of 4 Floors
53            9th   of 12 Floors
54            6th   of 10 Floors
55             2nd   of 4 Floors
56           14th   of 14 Floors
57            1st   of 11 Floors
58            8th   of 14 Floors
59             2nd   of 2 Floors
60           12nd   of 12 Floors
61            4th   of 14 Floors
62            1st   of 18 Floors
63            7th   of 19 Floors
64             3rd   of 4 Floors
65            5th   of 20 Floors
66            9th   of 15 Floors
67           14th   of 17 Floors
68           14th   of 14 Floors
69           15th   of 20 Floors
70            6th   of 14 Floors
71            6th   of 14 Floors
72            2nd   of 12 Floors
73            3rd   of 11 Floors
74             2nd   of 4 Floors
75            4th   of 13 Floors
76             3rd   of 4 Floors
77            6th   of 14 Floors
78            8th   of 13 Floors
79             2nd   of 4 Floors
80             4th   of 4 Floors
81           Ground of 14 Floors
82           11st   of 11 Floors
83             1st   of 3 Floors
84           11st   of 13 Floors
85           21st   of 41 Floors
86            4th   of 13 Floors
87             2nd   of 5 Floors
88             2nd   of 3 Floors
89             4th   of 4 Floors
90           32nd   of 32 Floors
91             2nd   of 4 Floors
92             2nd   of 2 Floors
93             2nd   of 2 Floors
94           11st   of 11 Floors
95           23rd   of 26 Floors
96            6th   of 12 Floors
97            9th   of 20 Floors
98             1st   of 4 Floors
99            5th   of 15 Floors
100            43   of 47 Floors
101            1st   of 1 Floors
102            1st   of 4 Floors
103           1st   of 13 Floors
104          11st   of 12 Floors
105          14th   of 24 Floors
106           9th   of 30 Floors
107           8th   of 14 Floors
108            9th   of 9 Floors
109           2nd   of 12 Floors
110           4th   of 14 Floors
111          32nd   of 55 Floors
112            43   of 47 Floors
113           2nd   of 19 Floors
114            3rd   of 4 Floors
115           8th   of 22 Floors
116            3rd   of 4 Floors
117          20th   of 32 Floors
118           2nd   of 17 Floors
119        Basement of 28 Floors
120           4th   of 10 Floors
121           Ground of 4 Floors
122            3rd   of 4 Floors
123            4th   of 8 Floors
124            3rd   of 4 Floors
125           6th   of 20 Floors
126          13rd   of 13 Floors
127          13rd   of 13 Floors
128          16th   of 16 Floors
129            3rd   of 4 Floors
130           Ground of 1 Floors
131          11st   of 14 Floors
132           2nd   of 14 Floors
133          12nd   of 12 Floors
134            2nd   of 4 Floors
135           1st   of 18 Floors
136           4th   of 12 Floors
137          11st   of 13 Floors
138           5th   of 17 Floors
139           1st   of 25 Floors
140          12nd   of 16 Floors
141          16th   of 18 Floors
142            6th   of 6 Floors
143            2nd   of 2 Floors
144            3rd   of 4 Floors
145          11st   of 25 Floors
146          10th   of 18 Floors
147           2nd   of 25 Floors
148            4th   of 4 Floors
149          19th   of 41 Floors
150            1st   of 3 Floors
151            8th   of 8 Floors
152          18th   of 19 Floors
153          10th   of 16 Floors
154           7th   of 20 Floors
155           2nd   of 14 Floors
156          10th   of 10 Floors
157           5th   of 12 Floors
158          10th   of 20 Floors
159          20th   of 34 Floors
160          20th   of 22 Floors
161            3rd   of 4 Floors
162          13rd   of 14 Floors
163           3rd   of 19 Floors
164           7th   of 18 Floors
165            4th   of 4 Floors
166           4th   of 14 Floors
167            2nd   of 4 Floors
168           2nd   of 25 Floors
169           4th   of 14 Floors
170           3rd   of 19 Floors
171            1st   of 1 Floors
172            2nd   of 4 Floors
173          11st   of 15 Floors
174          11st   of 21 Floors
175          16th   of 22 Floors
176           8th   of 10 Floors
177           1st   of 35 Floors
178          18th   of 25 Floors
179           8th   of 15 Floors
180                          NaN
181           2nd   of 16 Floors
182          17th   of 17 Floors
183          23rd   of 28 Floors
184          10th   of 18 Floors
185          30th   of 32 Floors
186            4th   of 4 Floors
187            2nd   of 3 Floors
188           Ground of 3 Floors
189          Ground of 14 Floors
190            1st   of 4 Floors
191            1st   of 1 Floors
192          11st   of 36 Floors
193          11st   of 13 Floors
194           Ground of 3 Floors
195          19th   of 19 Floors
196          28th   of 28 Floors
197            4th   of 4 Floors
198            9th   of 9 Floors
199            7th   of 7 Floors
200         Basement of 4 Floors
201          15th   of 15 Floors
202           2nd   of 34 Floors
203          Ground of 14 Floors
204           9th   of 10 Floors
205           1st   of 15 Floors
206            1st   of 1 Floors
207           4th   of 34 Floors
208           4th   of 18 Floors
209           3rd   of 15 Floors
210            1st   of 4 Floors
211           1st   of 19 Floors
212     Lower Ground of 4 Floors
213          13rd   of 13 Floors
214           4th   of 40 Floors
215           6th   of 18 Floors
216          20th   of 47 Floors
217          27th   of 48 Floors
218            6th   of 7 Floors
219          33rd   of 48 Floors
220          35th   of 35 Floors
221          26th   of 47 Floors
222           Ground of 1 Floors
223            2nd   of 4 Floors
224           4th   of 14 Floors
225          10th   of 17 Floors
226          11st   of 14 Floors
227          10th   of 22 Floors
228          Ground of 24 Floors
229           3rd   of 12 Floors
230           7th   of 25 Floors
231           8th   of 14 Floors
232            2nd   of 4 Floors
233           3rd   of 18 Floors
234            1st   of 4 Floors
235           9th   of 14 Floors
236          14th   of 15 Floors
237            4th   of 4 Floors
238           8th   of 25 Floors
239          10th   of 14 Floors
240           3rd   of 14 Floors
241            3rd   of 4 Floors
242            2nd   of 4 Floors
243           3rd   of 14 Floors
244            7th   of 7 Floors
245            2nd   of 4 Floors
246           3rd   of 15 Floors
247           8th   of 34 Floors
248          12nd   of 14 Floors
249           8th   of 42 Floors
250            1st   of 4 Floors
251           1st   of 22 Floors
252          26th   of 34 Floors
253          21st   of 29 Floors
254           8th   of 32 Floors
255           2nd   of 14 Floors
256           1st   of 12 Floors
257            2nd   of 4 Floors
258          39th   of 40 Floors
259           1st   of 14 Floors
260           8th   of 10 Floors
261            2nd   of 3 Floors
262            3rd   of 4 Floors
263            7th   of 9 Floors
264           4th   of 15 Floors
265          22nd   of 24 Floors
266          14th   of 20 Floors
267          11st   of 15 Floors
268          17th   of 17 Floors
269           3rd   of 12 Floors
270          12nd   of 13 Floors
271           8th   of 19 Floors
272           3rd   of 14 Floors
273          14th   of 14 Floors
274            7th   of 7 Floors
275           9th   of 15 Floors
276           2nd   of 17 Floors
277            3rd   of 3 Floors
278            6th   of 6 Floors
279          16th   of 16 Floors
280          12nd   of 12 Floors
281            1st   of 1 Floors
282            4th   of 4 Floors
283          17th   of 17 Floors
284           7th   of 26 Floors
286          11st   of 30 Floors
287            4th   of 8 Floors
288           1st   of 14 Floors
289           6th   of 14 Floors
290            1st   of 3 Floors
291          17th   of 17 Floors
292            1st   of 7 Floors
293          16th   of 18 Floors
294          19th   of 40 Floors
295          31st   of 32 Floors
296          14th   of 22 Floors
297           5th   of 19 Floors
298            2nd   of 4 Floors
299            1st   of 4 Floors
300           1st   of 10 Floors
301          15th   of 32 Floors
302            1st   of 7 Floors
303            1st   of 2 Floors
304            2nd   of 3 Floors
305          11st   of 14 Floors
306           9th   of 26 Floors
307          33rd   of 42 Floors
308          14th   of 18 Floors
309            4th   of 4 Floors
310           5th   of 14 Floors
311          18th   of 18 Floors
312           1st   of 14 Floors
313          20th   of 23 Floors
314           9th   of 14 Floors
315          18th   of 19 Floors
316           8th   of 32 Floors
317           4th   of 15 Floors
318           9th   of 17 Floors
319            4th   of 8 Floors
320           1st   of 14 Floors
321           6th   of 14 Floors
322            1st   of 3 Floors
323          19th   of 40 Floors
324          31st   of 32 Floors
325           5th   of 19 Floors
326            1st   of 4 Floors
327           1st   of 10 Floors
328          15th   of 32 Floors
329            1st   of 7 Floors
330            1st   of 2 Floors
331            2nd   of 3 Floors
332          11st   of 14 Floors
333           9th   of 26 Floors
334          14th   of 18 Floors
335           5th   of 14 Floors
336           1st   of 14 Floors
337           9th   of 14 Floors
338          18th   of 19 Floors
339           4th   of 15 Floors
340           1st   of 44 Floors
341          20th   of 20 Floors
342          24th   of 31 Floors
343           2nd   of 15 Floors
344            4th   of 4 Floors
345          14th   of 14 Floors
346           9th   of 16 Floors
347          14th   of 15 Floors
348           4th   of 14 Floors
349          26th   of 30 Floors
350           2nd   of 16 Floors
351          14th   of 24 Floors
352          17th   of 17 Floors
353           2nd   of 14 Floors
354          25th   of 25 Floors
355           9th   of 22 Floors
356            4th   of 4 Floors
357           6th   of 17 Floors
358           5th   of 14 Floors
359           4th   of 14 Floors
360          14th   of 21 Floors
361          15th   of 19 Floors
362           7th   of 14 Floors
363            2nd   of 4 Floors
364          16th   of 20 Floors
365          24th   of 51 Floors
366          10th   of 20 Floors
367            2nd   of 4 Floors
368           2nd   of 12 Floors
369           2nd   of 24 Floors
370           1st   of 19 Floors
371           8th   of 18 Floors
372          12nd   of 22 Floors
373          18th   of 19 Floors
374            1st   of 4 Floors
375           2nd   of 36 Floors
376            3rd   of 4 Floors
377          11st   of 11 Floors
378           7th   of 20 Floors
379           5th   of 18 Floors
380           6th   of 12 Floors
381          19th   of 31 Floors
382          25th   of 25 Floors
383          10th   of 10 Floors
384          10th   of 10 Floors
385            3rd   of 9 Floors
386           8th   of 14 Floors
387           5th   of 12 Floors
388           4th   of 22 Floors
389           1st   of 35 Floors
390          10th   of 14 Floors
391          16th   of 24 Floors
392          10th   of 14 Floors
393            3rd   of 8 Floors
394          17th   of 19 Floors
395           9th   of 14 Floors
396          11st   of 26 Floors
397          19th   of 20 Floors
398          Ground of 16 Floors
399          Ground of 23 Floors
400           8th   of 26 Floors
401           4th   of 11 Floors
402          30th   of 32 Floors
403          16th   of 51 Floors
404          18th   of 21 Floors
405           2nd   of 10 Floors
406           7th   of 10 Floors
407            2nd   of 4 Floors
408          10th   of 10 Floors
409           9th   of 12 Floors
410           6th   of 10 Floors
411          14th   of 29 Floors
412          25th   of 36 Floors
413           7th   of 23 Floors
414           4th   of 14 Floors
415            7th   of 9 Floors
416          18th   of 32 Floors
417          12nd   of 17 Floors
418            3rd   of 4 Floors
419          21st   of 28 Floors
420          14th   of 28 Floors
421           5th   of 25 Floors
422           3rd   of 19 Floors
423          19th   of 24 Floors
424          10th   of 14 Floors
425            5th   of 9 Floors
426          10th   of 30 Floors
427           7th   of 14 Floors
428          11st   of 20 Floors
429           2nd   of 17 Floors
430            2nd   of 4 Floors
431           7th   of 14 Floors
432           6th   of 14 Floors
433          11st   of 17 Floors
434           9th   of 14 Floors
435            4th   of 4 Floors
436          14th   of 20 Floors
437            5th   of 5 Floors
438            1st   of 4 Floors
439          16th   of 27 Floors
440           1st   of 10 Floors
441          18th   of 32 Floors
442           6th   of 16 Floors
443           8th   of 13 Floors
444            4th   of 4 Floors
445           7th   of 27 Floors
446            9th   of 9 Floors
447            3rd   of 4 Floors
448          11st   of 18 Floors
449          17th   of 25 Floors
450           7th   of 42 Floors
451           5th   of 30 Floors
452          16th   of 32 Floors
453           2nd   of 16 Floors
454           8th   of 29 Floors
455            2nd   of 8 Floors
456           3rd   of 32 Floors
457           6th   of 26 Floors
458          Ground of 14 Floors
459           2nd   of 12 Floors
460          15th   of 40 Floors
461          10th   of 25 Floors
462          11st   of 30 Floors
463          10th   of 15 Floors
464           4th   of 12 Floors
465           3rd   of 18 Floors
466           9th   of 19 Floors
467           8th   of 16 Floors
468           7th   of 12 Floors
469           5th   of 12 Floors
470           7th   of 14 Floors
471           7th   of 14 Floors
472           9th   of 14 Floors
473           2nd   of 20 Floors
474           5th   of 18 Floors
475          11st   of 20 Floors
476           8th   of 11 Floors
477           7th   of 17 Floors
478          20th   of 26 Floors
479          10th   of 12 Floors
480           7th   of 29 Floors
481          10th   of 51 Floors
482          16th   of 21 Floors
483           8th   of 21 Floors
484           1st   of 14 Floors
485          18th   of 30 Floors
486          15th   of 30 Floors
487          25th   of 30 Floors
488           5th   of 29 Floors
489           9th   of 26 Floors
490           5th   of 26 Floors
491           7th   of 26 Floors
492           7th   of 26 Floors
493           7th   of 26 Floors
494          12nd   of 30 Floors
495           5th   of 15 Floors
496           4th   of 10 Floors
497           6th   of 10 Floors
498            3rd   of 6 Floors
499          10th   of 18 Floors
500          15th   of 28 Floors
501          15th   of 28 Floors
502          10th   of 14 Floors
503           9th   of 28 Floors
504          10th   of 15 Floors
505          10th   of 21 Floors
506           9th   of 12 Floors
507           Ground of 4 Floors
508            1st   of 2 Floors
509          11st   of 12 Floors
510          17th   of 24 Floors
511           1st   of 26 Floors
512          Ground of 18 Floors
513           7th   of 14 Floors
514            5th   of 8 Floors
515          12nd   of 29 Floors
516          14th   of 29 Floors
517          14th   of 29 Floors
518           9th   of 21 Floors
519          19th   of 29 Floors
520           8th   of 14 Floors
521          14th   of 29 Floors
522           8th   of 14 Floors
523            2nd   of 5 Floors
524           9th   of 13 Floors
525           5th   of 14 Floors
526          Ground of 14 Floors
527            6th   of 8 Floors
528          10th   of 19 Floors
529           6th   of 10 Floors
530           8th   of 18 Floors
531           9th   of 24 Floors
532           9th   of 26 Floors
533          12nd   of 17 Floors
534          11st   of 16 Floors
535           6th   of 16 Floors
536          15th   of 39 Floors
537           7th   of 12 Floors
538           8th   of 19 Floors
539           8th   of 26 Floors
540           3rd   of 26 Floors
541          10th   of 26 Floors
542           1st   of 26 Floors
543           4th   of 26 Floors
544           5th   of 12 Floors
545           2nd   of 12 Floors
546          20th   of 40 Floors
547          13rd   of 40 Floors
548           8th   of 40 Floors
549           8th   of 19 Floors
550          16th   of 19 Floors
551          12nd   of 18 Floors
552          10th   of 19 Floors
553           6th   of 15 Floors
554          16th   of 19 Floors
555           8th   of 16 Floors
556          12nd   of 15 Floors
557          12nd   of 18 Floors
558           5th   of 22 Floors
559           9th   of 42 Floors
560           7th   of 14 Floors
561           7th   of 12 Floors
562           7th   of 12 Floors
563           5th   of 16 Floors
564           8th   of 31 Floors
565           7th   of 21 Floors
566           5th   of 29 Floors
567           9th   of 30 Floors
568          11st   of 29 Floors
569          10th   of 19 Floors
570           6th   of 31 Floors
571            3rd   of 9 Floors
572          22nd   of 30 Floors
573           5th   of 20 Floors
574          15th   of 29 Floors
575           5th   of 14 Floors
576          Ground of 14 Floors
577           6th   of 14 Floors
578           1st   of 24 Floors
579            2nd   of 8 Floors
580          12nd   of 19 Floors
581          12nd   of 25 Floors
582           6th   of 17 Floors
583           8th   of 18 Floors
584            4th   of 5 Floors
585           5th   of 25 Floors
586           2nd   of 19 Floors
587          20th   of 30 Floors
588          12nd   of 14 Floors
589          18th   of 19 Floors
590           2nd   of 26 Floors
591           3rd   of 15 Floors
592           3rd   of 19 Floors
593          18th   of 51 Floors
594           7th   of 27 Floors
595          17th   of 19 Floors
596           8th   of 14 Floors
597           2nd   of 19 Floors
598           8th   of 19 Floors
599           9th   of 30 Floors
600           3rd   of 18 Floors
601          12nd   of 23 Floors
602          10th   of 28 Floors
603            2nd   of 5 Floors
604          Ground of 21 Floors
605           7th   of 16 Floors
606            2nd   of 9 Floors

In [66]:
df['floorNum'].isnull().sum()

2

In [67]:
df[df['floorNum'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
180,3 BHK Flat in Dwarka Expressway Gurgaon,experion heartsong,1.08,6150.0,Built Up area: 1758 (163.32 sq.m.),3,3,0,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN
2759,2 BHK Flat in Sector 78 Gurgaon,NaN,0.60,3692.0,Built Up area: 1625 (150.97 sq.m.),2,2,0,not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [68]:
df['floorNum']=  df['floorNum'].str.split(' ')

In [69]:
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
330,1 BHK Flat in Sector 28 Gurgaon,maruti vihar,1.00,9090.0,Super Built up area 1100(102.19 sq.m.),1,1,1,"pooja room,study room","Sector 28 Gurgaon, Gurgaon, Haryana","[1st , of, 2, Floors]",North,10+ Year Old,"['Mg road metro station', 'Iffco chowk metro s...",We are the proud owners of this 1 bhk apartmen...,"['6 Wardrobe', '3 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Private Garden / Te...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
1847,2 BHK Flat in Sector 90 Gurgaon,shree vardhman flora,0.65,4814.0,Super Built up area 1350(125.42 sq.m.),2,2,3,study room,"306, Sector 90 Gurgaon, Gurgaon, Haryana","[6th , of, 14, Floors]",West,1 to 5 Year Old,"['IRIS Broadway Mall', 'Dwarka Expressway', 'S...","Shree vardhman flora in sector 90, gurgaon is ...",NaN,"['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
609,3 BHK Flat in Sector 82 Gurgaon,vatika the seven lamps,1.28,6819.0,Super Built up area 1877(174.38 sq.m.)Built Up...,3,3,3,study room,"303, Sector 82 Gurgaon, Gurgaon, Haryana","[3rd , of, 16, Floors]",North,1 to 5 Year Old,"['SS Omnia Mall', 'Golf Course Ext Rd', 'Knowl...",This beautiful 3 bhk flat in sector 82 gurgaon...,"['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '3 Ge...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction5 out of..."
1372,3 BHK Flat in Sector 65 Gurgaon,emaar mgf emerald floors premier,2.30,13939.0,Carpet area: 1650 (153.29 sq.m.),3,4,3,"pooja room,study room,servant room,store room","Sector 65 Gurgaon, Gurgaon, Haryana","[3rd , of, 5, Floors]",South-West,1 to 5 Year Old,"['WorldMark Gurgaon', 'Sohna Road', 'Golf Cour...","Emerald floors premier, located in sector 65, ...","['1 Water Purifier', '1 Fan', '1 Fridge', '1 E...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction5 out ..."
418,2 BHK Flat in Sector 30 Gurgaon,afnhb jalvayu vihar,0.69,7272.0,Super Built up area 990(91.97 sq.m.),2,2,1,not available,"Sector 30 Gurgaon, Gurgaon, Haryana","[3rd , of, 4, Floors]",North-East,10+ Year Old,"['Icici bank ATM', 'Hdfc ATM', 'Axis bank ATM'...","2bhk, fully furnished, in jal vayu vihar, sect...","['1 Bed', '1 Wardrobe', '1 Fan', '1 Sofa', '1 ...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4.5 out of 5', 'Construction4 out ..."

In [70]:
df['floorNum'] = df['floorNum'].str.get(0).replace('Ground', '0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

In [71]:
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
856,3 BHK Flat in Sector 102 Gurgaon,shapoorji pallonji joyville gurugram,2.00,10799.0,Super Built up area 1852(172.06 sq.m.),3,3,3,not available,"Sector 102 Gurgaon, Gurgaon, Haryana",9,South-East,1 to 5 Year Old,"['Khan Market', 'The Esplanade Mall', 'Dwarka ...",Best amenities and best construction quality. ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction5 out of..."
98,3 BHK Flat in Sector 63A Gurgaon,signature global city 63a,2.00,12800.0,Built Up area: 1540 (143.07 sq.m.),3,3,2,not available,"Sector 63A Gurgaon, Gurgaon, Haryana",1,North,2024-10-01 00:00:00,"['Sector 54 Chowk Metro Station', 'Paras Trini...","North facing, park and club facing","['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety5 out of 5', ..."
1493,3 BHK Flat in Sector 66 Gurgaon,emaar mgf the palm drive,3.50,15909.0,Super Built up area 2200(204.39 sq.m.)Built Up...,3,3,3,"servant room,store room","706, Sector 66 Gurgaon, Gurgaon, Haryana",7,North-East,5 to 10 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",Emaar palm drive flat for immediate sale with ...,"['4 Wardrobe', '7 Fan', '1 Exhaust Fan', '5 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4.5 out ..."
986,2 BHK Flat in Sector 85 Gurgaon,ss the leaf,1.22,13318.0,Super Built up area 1772(164.62 sq.m.)Built Up...,2,2,3,store room,"Sector 85 Gurgaon, Gurgaon, Haryana",16,North-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","Ss the leaf in sector 85, gurgaon is a ready-T...","['4 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Intercom Facility', 'Lift(s)', 'High Ceiling...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
327,4 BHK Flat in Sector 9A Gurgaon,railway officers rpf society,1.25,6921.0,Carpet area: 1806 (167.78 sq.m.),4,3,3,servant room,"101, Tower A, Sector 9A Gurgaon, Gurgaon, Haryana",1,South-West,10+ Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Esic...",4bhk flat/apartment for sale in rpf housing so...,"['3 Wardrobe', '1 Exhaust Fan', '3 Geyser', '1...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [3]:
df= pd.read_csv('worktill250920242.csv')

In [4]:
df.sample(5)

,Unnamed: 0,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1685,1686,3 BHK Flat in Sector 71 Gurgaon,chd avenue,1.25,7171.0,Super Built up area 1743(161.93 sq.m.),3,4,2,servant room,"T 7 701, Sector 71 Gurgaon, Gurgaon, Haryana",7.0,East,1 to 5 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",Chd avenue 71 is one of gurgaon's most sought ...,"['4 Fan', '1 Exhaust Fan', '3 Geyser', '10 Lig...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction3 out of..."
1176,1177,3 BHK Flat in Sector 85 Gurgaon,ss the leaf,1.85,7682.0,Super Built up area 2408(223.71 sq.m.),3,4,3,"study room,servant room","Sector 85 Gurgaon, Gurgaon, Haryana",2.0,North,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...",Located in the popular residential address of ...,"['1 Exhaust Fan', '3 Geyser', '1 Stove', '5 AC...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
2071,2072,3 BHK Flat in Sector 70A Gurgaon,aipl peaceful homes,2.75,12791.0,Built Up area: 2150 (199.74 sq.m.),3,3,3+,not available,"Sector 70a, Sector 70A Gurgaon, Gurgaon, Haryana",14.0,North-East,undefined,"['Sri Radhe Krishna Temple', 'Sai Dharamraj Ho...",A naturally very lit home in a friendly neighb...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
1212,1213,4 BHK Flat in Sector 90 Gurgaon,dlf new town heights,2.00,7334.0,Super Built up area 2727(253.35 sq.m.),4,4,3+,"servant room,others","Sector 90 Gurgaon, Gurgaon, Haryana",20.0,East,5 to 10 Year Old,"['Manish Gallexie 91', 'NH-8 IMT Manesar', 'RH...",Located in the popular residential address of ...,[],"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."
821,822,3 BHK Flat in Sector 109 Gurgaon,sbtl caladium,1.26,6542.0,Super Built up area 1880(174.66 sq.m.),3,2,3,not available,"N/a, Sector 109 Gurgaon, Gurgaon, Haryana",8.0,North-East,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Chirag Hospital...",Looking for a 3 bhk property for sale in gurga...,[],"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."

In [8]:
df[df['floorNum'].isna()]

,Unnamed: 0,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
180,180,3 BHK Flat in Dwarka Expressway Gurgaon,experion heartsong,1.08,6150.0,Built Up area: 1758 (163.32 sq.m.),3,3,0,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN
2758,2759,2 BHK Flat in Sector 78 Gurgaon,NaN,0.60,3692.0,Built Up area: 1625 (150.97 sq.m.),2,2,0,not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [13]:
df['floorNum'] = df['floorNum'].fillna(0)

In [14]:
df['floorNum'].isna().sum()

0

In [16]:
df['floorNum']= df['floorNum'].astype('int')

In [17]:
df.sample(5)

,Unnamed: 0,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
677,678,4 BHK Flat in Sector 49 Gurgaon,bestech park view city,2.90,12169.0,Super Built up area 2383(221.39 sq.m.),4,4,3+,servant room,"D 5floor, Sector 49 Gurgaon, Gurgaon, Haryana",5,South-West,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Raheja Mall', ...",This lovely 4 bhk apartment/flat in sector 49 ...,"['1 Geyser', '1 Light', 'No AC', 'No Bed', 'No...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4 out of..."
146,146,3 BHK Flat in Sohna,eldeco accolade,1.30,7424.0,Super Built up area 1751(162.67 sq.m.)Carpet a...,3,3,3+,not available,"Sohna, Gurgaon, Haryana",10,East,1 to 5 Year Old,"['Global City Centre', 'Sohna Road', 'Damdama ...",Spacious layout on sohna road.,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Amenities5 out of 5'..."
1043,1044,3 BHK Flat in Sector 30 Gurgaon,unitech uniworld city,3.55,14991.0,Super Built up area 2368(219.99 sq.m.)Built Up...,3,5,3+,servant room,"Uniworld City, Sector 30 Gurgaon, Gurgaon, Har...",16,North,10+ Year Old,"['Needs Supermarket', 'Ryan International Scho...",Check out this 3 bhk apartment for sale in uni...,"['6 Fan', '1 Exhaust Fan', '21 Light', '5 AC',...","['Water purifier', 'Centrally Air Conditioned'...","['Green Area3.5 out of 5', 'Construction4.5 ou..."
2410,2411,4 BHK Flat in Sector 109 Gurgaon,raheja atharva,1.60,5319.0,Built Up area: 3008 (279.45 sq.m.),4,1,0,not available,"Sector 109, Sector 109 Gurgaon, Gurgaon, Haryana",0,NaN,0 to 1 Year Old,"['Indiabulls One 09', 'Dwarka Expressway', 'Gy...",Best in class property available at sector 109...,NaN,NaN,"['Green Area4 out of 5', 'Construction2 out of..."
1139,1140,3 BHK Flat in Sector 69 Gurgaon,tulip violet,1.32,8411.0,Super Built up area 1568(145.67 sq.m.),3,3,1,pooja room,"12th Floor, Sector 69 Gurgaon, Gurgaon, Haryana",12,South-West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Tulip violet is one of gurgaon's most sought a...,"['2 Wardrobe', '6 Fan', '1 Exhaust Fan', '9 Li...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction4 out of..."

In [18]:
# facing

df['facing'].value_counts()

facing
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [20]:
df['facing'].isnull().sum()

874

In [21]:
df['facing'].fillna('Na', inplace = True)

In [22]:
df['facing'].value_counts()

facing
Na            874
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [23]:
df.insert(loc=4, column='Area',value = round((df['price']*10000000)/df['price_per_sqft']))

In [24]:
df.head(5)

,Unnamed: 0,property_name,society,price,Area,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,900.0,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,650.0,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,595.0,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,Na,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,1200.0,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,Na,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,1345.0,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,Na,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [25]:
df.insert(loc = 2, column='property_type', value = 'flat')

In [26]:
df.head(5)

,Unnamed: 0,property_name,property_type,society,price,Area,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,900.0,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,650.0,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,595.0,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,Na,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,1200.0,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,Na,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,1345.0,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,Na,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [31]:
df.drop('Unnamed: 0', axis=1, inplace = True)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2997 entries, 0 to 2996
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2997 non-null   object
 1   property_type    2997 non-null   object
 2   society          2996 non-null   object
 3   price            2996 non-null   float64
 4   Area             2996 non-null   float64
 5   price_per_sqft   2996 non-null   float64
 6   areaWithType     2997 non-null   object
 7   bedRoom          2997 non-null   int64
 8   bathroom         2997 non-null   int64
 9   balcony          2997 non-null   object
 10  additionalRoom   2997 non-null   object
 11  address          2991 non-null   object
 12  floorNum         2997 non-null   int32
 13  facing           2997 non-null   object
 14  agePossession    2996 non-null   object
 15  nearbyLocations  2906 non-null   object
 16  description      2997 non-null   object
 17  furnishDetails   2200 non-null   object
 18  features         2590 non-null   object
 19  rating           2668 non-null   object
dtypes: float64(3), int32(1), int64(2), object(14)
memory usage: 456.7+ KB

In [33]:
df.head(5)

,property_name,property_type,society,price,Area,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,900.0,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,650.0,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,595.0,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,Na,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,1200.0,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,Na,2023-12-01 00:00:00,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,1345.0,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,Na,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [34]:
df.shape

(2997, 20)

In [36]:
df['floorNum'] = df['floorNum'].astype('object')

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2997 entries, 0 to 2996
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2997 non-null   object
 1   property_type    2997 non-null   object
 2   society          2996 non-null   object
 3   price            2996 non-null   float64
 4   Area             2996 non-null   float64
 5   price_per_sqft   2996 non-null   float64
 6   areaWithType     2997 non-null   object
 7   bedRoom          2997 non-null   int64
 8   bathroom         2997 non-null   int64
 9   balcony          2997 non-null   object
 10  additionalRoom   2997 non-null   object
 11  address          2991 non-null   object
 12  floorNum         2997 non-null   object
 13  facing           2997 non-null   object
 14  agePossession    2996 non-null   object
 15  nearbyLocations  2906 non-null   object
 16  description      2997 non-null   object
 17  furnishDetails   2200 non-null   object
 18  features         2590 non-null   object
 19  rating           2668 non-null   object
dtypes: float64(3), int64(2), object(15)
memory usage: 468.4+ KB

In [39]:
df.to_csv('flats_cleaned.csv',index=False)